# Generated by Django 5.0.1 on 2025-11-24 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_key', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=200)),
                ('file_extension', models.CharField(max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('failed', 'Scan Failed')], db_index=True, default='pending', max_length=20)),
                ('scan_result', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('chat_message_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('uploaded_by_id', models.UUIDField(db_index=True)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket_id'], name='attachments_ticket__43ed4e_idx'), models.Index(fields=['chat_message_id'], name='attachments_chat_me_08c87c_idx'), models.Index(fields=['uploaded_by_id'], name='attachments_uploade_77499a_idx'), models.Index(fields=['scan_status'], name='attachments_scan_st_60b515_idx'), models.Index(fields=['created_at'], name='attachments_created_d487af_idx')],
            },
        ),
    ]
