# Generated by Django 4.2 on 2026-01-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='category',
            field=models.CharField(db_index=True, default='general', help_text='Collection/Folder name (e.g., resumes, tickets)', max_length=50),
        ),
    ]
