# Generated by Django 5.0.1 on 2026-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_attachment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
