# Generated by Django 5.0.6 on 2026-01-14 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lms_account_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='lms_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='receipt_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='receipt_code_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReceiptCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_name', models.CharField(max_length=255)),
                ('test_score', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('added_to_system_at', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('lms_account_created', models.BooleanField(default=False)),
                ('lms_user_id', models.UUIDField(blank=True, null=True)),
                ('added_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_receipt_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Receipt Codes',
            },
        ),
    ]
