# Generated by Django 5.0.6 on 2026-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_lms_account_created_student_lms_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcode',
            name='course_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
