# Generated by Django 5.0.6 on 2026-02-28 05:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_info',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_info',
        ),
        migrations.RemoveField(
            model_name='student',
            name='residential_info',
        ),
        migrations.AlterField(
            model_name='student',
            name='completed_courses',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='student',
            name='eligible_course',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_info', to='users.student')),
            ],
            options={
                'verbose_name_plural': 'Guardian Information',
            },
        ),
        migrations.CreateModel(
            name='ResidentialInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_or_province', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residential_info', to='users.student')),
            ],
            options={
                'verbose_name_plural': 'Residential Information',
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_name', models.CharField(blank=True, max_length=255, null=True)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('grade_or_cgpa', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_record', to='users.student')),
            ],
            options={
                'verbose_name_plural': 'Student Academic Records',
            },
        ),
    ]
