# Generated by Django 5.0.6 on 2026-04-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_cnic_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
