# Generated by Django 5.0.6 on 2026-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student_terms_agreed_student_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcode',
            name='scheduled_class_id',
            field=models.UUIDField(blank=True, help_text='Session selected by student at registration', null=True),
        ),
    ]
