# Generated by Django 5.0.6 on 2026-04-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_receiptcode_scheduled_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianinfo',
            name='relationship_to_student',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studied_at_idara',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='study_work_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='study_work_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studying_at_idara',
            field=models.BooleanField(default=False),
        ),
    ]
