# Generated by Django 5.0.6 on 2026-04-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role_teacherattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcode',
            name='amount_returned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='bag_fee',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='bag_taken',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='deposit_amount',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='id_card_fee',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='id_card_taken',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiptcode',
            name='test_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
