# Generated by Django 5.0.6 on 2026-04-12 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_receiptcode_amount_returned_receiptcode_bag_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransferHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_course_id', models.UUIDField()),
                ('to_course_id', models.UUIDField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='users.receiptcode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='users.student')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
