# Generated by Django 5.0.6 on 2026-04-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_studenttransferhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, default='Level 1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
