# Generated by Django 5.0.6 on 2026-04-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_adminactionlog_receiptcode_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransferhistory',
            name='from_section_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttransferhistory',
            name='to_section_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
