# Generated by Django 5.0.6 on 2026-04-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_studenttransferhistory_from_section_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='features_access',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
