# Generated by Django 5.0.6 on 2026-04-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rolepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='features_access',
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
