# Generated by Django 5.0.6 on 2026-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_user_features_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='features_access',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
