# Generated by Django 5.0.6 on 2026-05-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_features_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_paid_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='test_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
