# Generated by Django 5.0.6 on 2026-05-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_add_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
