# Generated by Django 5.0.6 on 2026-05-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_fix_last_login_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcode',
            name='bag_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='bag_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='id_card_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='id_card_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='is_waived',
            field=models.BooleanField(default=False),
        ),
    ]
