# Generated by Django 5.0.6 on 2026-06-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_receiptcode_certificate_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptcode',
            name='bag_fee',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='receiptcode',
            name='deposit_amount',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='receiptcode',
            name='id_card_fee',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('coordinator', 'Coordinator'), ('account_officer', 'Account Officer'), ('lead', 'Lead')], default='student', max_length=20),
        ),
    ]
