# Generated by Django 5.0.6 on 2026-07-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_receiptcode_bag_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcode',
            name='campus_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Campus', null=True),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='campus_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Campus', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='campus_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Campus', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='campus_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Campus', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
    ]
