# Generated by Django 5.0.6 on 2025-12-02 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(help_text='Unique course code (e.g., "CS101", "AI-PYTHON")', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructor_id', models.CharField(blank=True, help_text='Instructor will be assigned when schedule is created', max_length=100, null=True)),
                ('category', models.CharField(blank=True, help_text='Course category/type', max_length=100, null=True)),
                ('level', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], help_text='Course difficulty level', max_length=20, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, help_text='Course duration', null=True)),
                ('duration_unit', models.CharField(blank=True, default='hours', help_text='Duration unit (hours, days, weeks, months)', max_length=10, null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Course thumbnail image', null=True, upload_to='courses/thumbnails/')),
                ('attachment', models.FileField(blank=True, help_text='Course attachment (PDF, DOC, etc.)', null=True, upload_to='courses/attachments/')),
                ('intro_video', models.URLField(blank=True, help_text='Course intro video URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'courses_course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Detailed instructions for the assignment')),
                ('total_marks', models.IntegerField(default=100, help_text='Total marks for this assignment')),
                ('due_date', models.DateTimeField()),
                ('assignment_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('PROJECT', 'Project'), ('QUIZ', 'Quiz'), ('EXAM', 'Exam'), ('ESSAY', 'Essay'), ('OTHER', 'Other')], default='HOMEWORK', help_text='Type of assignment', max_length=20)),
                ('is_published', models.BooleanField(default=False, help_text='Whether assignment is published and visible to students')),
                ('created_by_id', models.IntegerField(help_text='ID of the teacher who created this assignment')),
                ('attachment', models.FileField(blank=True, help_text='Attach files (images, documents, PDFs, etc.)', null=True, upload_to='assignments/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'db_table': 'courses_assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course')),
            ],
            options={
                'db_table': 'courses_announcement',
                'ordering': ['-created_at'],
            },
        ),

        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, db_column='section_name', help_text='Name of the class/section (e.g., "Morning Batch", "Evening Batch")', max_length=255, null=True)),
                ('instructor_id', models.CharField(blank=True, db_column='instructor_id', help_text='Instructor UUID from auth-service', max_length=100, null=True)),
                ('days', models.JSONField(blank=True, db_column='class_days', default=list, help_text='Selected days as array ["Monday", "Wednesday", "Friday"]', null=True)),
                ('room', models.CharField(blank=True, db_column='room_number', help_text='Room/location (e.g., "1A", "Room 101", "Lab 2")', max_length=100, null=True)),
                ('max_students', models.IntegerField(blank=True, help_text='Maximum students', null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='courses.course')),
            ],
            options={
                'db_table': 'courses_scheduledclass',
                'ordering': ['time_slot__start_time', 'class_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of the class session')),
                ('marked_by', models.CharField(help_text='Instructor ID who marked the attendance', max_length=100)),
                ('total_students', models.PositiveIntegerField(default=0, help_text='Total students in the class')),
                ('present_count', models.PositiveIntegerField(default=0, help_text='Number of present students')),
                ('absent_count', models.PositiveIntegerField(default=0, help_text='Number of absent students')),
                ('late_count', models.PositiveIntegerField(default=0, help_text='Number of late students')),
                ('leave_count', models.PositiveIntegerField(default=0, help_text='Number of students on leave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_class', models.ForeignKey(help_text='Scheduled class for this attendance', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.scheduledclass')),
            ],
            options={
                'db_table': 'courses_attendance',
                'ordering': ['-date', 'scheduled_class'],
                'unique_together': {('scheduled_class', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_name', models.CharField(help_text='Display name like "3-5 PM", "1:30-3:00 PM"', max_length=50, unique=True)),
                ('start_time', models.TimeField(help_text='Start time (e.g., 15:00 for 3 PM, 13:30 for 1:30 PM)')),
                ('end_time', models.TimeField(help_text='End time (e.g., 17:00 for 5 PM, 15:00 for 3 PM)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this time slot is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses_timeslot',
                'ordering': ['start_time'],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='time_slot',
            field=models.ForeignKey(blank=True, db_column='time_slot_id', help_text='Predefined time slot', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_classes', to='courses.timeslot'),
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(help_text='ID of the student who submitted')),
                ('submission_file_url', models.CharField(blank=True, db_column='submission_file_url', help_text='URL/path to student submission file', max_length=200, null=True)),
                ('submission_text', models.TextField(blank=True, help_text='Optional text submission', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('RETURNED', 'Returned'), ('LATE', 'Late Submission')], default='SUBMITTED', help_text='Submission status', max_length=20)),
                ('marks_obtained', models.IntegerField(blank=True, db_column='marks_obtained', help_text='Marks obtained out of total marks', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Teacher feedback', null=True)),
                ('graded_by_id', models.IntegerField(blank=True, help_text='ID of teacher who graded', null=True)),
                ('graded_at', models.DateTimeField(blank=True, help_text='When assignment was graded', null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment')),
            ],
            options={
                'db_table': 'courses_assignmentsubmission',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0, help_text='Course progress percentage')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time student accessed the course')),
                ('is_active', models.BooleanField(default=True, help_text='Whether enrollment is active')),
                ('completion_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='IN_PROGRESS', help_text='Status of course completion', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date when course was completed', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('scheduled_class', models.ForeignKey(blank=True, db_column='scheduled_class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.scheduledclass')),
            ],
            options={
                'db_table': 'courses_courseenrollment',
                'unique_together': {('course', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(help_text='Student ID from auth-service')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave')], default='present', help_text='Attendance status', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(help_text='Attendance record this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='courses.attendance')),
            ],
            options={
                'db_table': 'courses_studentattendance',
                'ordering': ['student_id'],
                'unique_together': {('attendance', 'student_id')},
            },
        ),
    ]
