# Generated by Django 5.0.6 on 2025-12-03 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('PRESENTATION', 'Presentation'), ('LINK', 'External Link')], default='DOCUMENT', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Upload file (PDF, PPT, DOC, etc.)', null=True, upload_to='courses/content/')),
                ('url', models.URLField(blank=True, help_text='External URL (YouTube, Drive, etc.)', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.course')),
            ],
            options={
                'db_table': 'courses_content',
                'ordering': ['-created_at'],
            },
        ),
    ]
