# Generated by Django 4.2.11 on 2026-07-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_internal_visit_purpose'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employee',
            new_name='visitors_em_employe_775eb6_idx',
            old_name='visitors_em_employee_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='visitors_em_email_b29216_idx',
            old_name='visitors_em_email_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='visitors_em_departm_28021b_idx',
            old_name='visitors_em_departme_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visitors_vi_status_1b35dd_idx',
            old_name='visitors_vi_status_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visitors_vi_checked_984d5f_idx',
            old_name='visitors_vi_checked_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visitors_vi_visitin_df4cdf_idx',
            old_name='visitors_vi_vid_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visitors_vi_created_7586ba_idx',
            old_name='visitors_vi_created_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visitors_vi_purpose_49d406_idx',
            old_name='visitors_vi_purpose_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='visitor',
            new_name='visitors_vi_cnic_5f8929_idx',
            old_name='visitors_vi_cnic_idx',
        ),
        migrations.RenameIndex(
            model_name='visitor',
            new_name='visitors_vi_phone_3827a1_idx',
            old_name='visitors_vi_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='visitor',
            new_name='visitors_vi_email_e17823_idx',
            old_name='visitors_vi_email_idx',
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='purpose',
            field=models.CharField(blank=True, choices=[('interview', 'Interview'), ('meeting', 'Meeting'), ('delivery', 'Delivery/Courier'), ('contractor', 'Contractor/Worker'), ('official', 'Official Visit'), ('vip', 'VIP/Client/Donor'), ('internal', 'Internal Visit (Own Campus/College/Hospital)'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
