# Generated by Django 4.2.11 on 2026-07-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_rename_visitors_em_employee_123456_idx_visitors_em_employe_775eb6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('tenant_id', models.UUIDField()),
                ('label', models.CharField(blank=True, help_text="e.g. 'Main Gate — Idara Al-Khair'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
