# Generated by Django 5.2.17 on 2026-08-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principals', '0003_remove_evening_shift_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='central_user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
