# Generated by Django 5.0.6 on 2026-01-19 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('audience_type', models.CharField(choices=[('ALL', 'All Users'), ('ROLE', 'Role Based'), ('COURSE', 'Course Specific'), ('CLASS', 'Class Specific'), ('CUSTOM', 'Custom Recipients')], max_length=20)),
                ('target_role', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('COORDINATOR', 'Coordinator'), ('ADMIN', 'Admin'), ('ALL', 'All Roles')], default='ALL', help_text='Role filter to apply when broadcasting to ALL/ROLE audiences', max_length=20)),
                ('course_id', models.UUIDField(blank=True, help_text='Target course for COURSE audience type', null=True)),
                ('scheduled_class_id', models.UUIDField(blank=True, help_text='Target class for CLASS audience type', null=True)),
                ('created_by_id', models.UUIDField(help_text='User ID of the broadcaster')),
                ('created_by_role', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('COORDINATOR', 'Coordinator'), ('ADMIN', 'Admin'), ('ALL', 'All Roles')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('batch_id', models.CharField(blank=True, help_text='Optional idempotency batch identifier', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications_broadcasts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audience_type'], name='notif_audience_idx'), models.Index(fields=['created_by_id'], name='notif_created_by_idx'), models.Index(fields=['batch_id'], name='notif_batch_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.UUIDField(help_text='User ID from auth-service')),
                ('recipient_role', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('COORDINATOR', 'Coordinator'), ('ADMIN', 'Admin'), ('ALL', 'All Roles')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationbroadcast')),
            ],
            options={
                'db_table': 'notifications_deliveries',
                'ordering': ['-delivered_at'],
                'indexes': [models.Index(fields=['recipient_id', 'is_read'], name='notif_recipient_read_idx'), models.Index(fields=['broadcast'], name='notif_broadcast_idx')],
            },
        ),
    ]
