# Generated by Django 5.0.6 on 2026-07-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationbroadcast',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
    ]
