# Generated by Django 5.2.17 on 2026-08-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='central_approved_by_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='central_created_by_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='central_org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='central_created_by_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        # Phase C11: makemigrations also proposed an AlterField changing
        # Invoice.id from AutoField to BigAutoField — a pre-existing drift
        # between migration history and DEFAULT_AUTO_FIELD (unrelated to
        # central-auth, predates this phase). Deliberately dropped from
        # this migration to keep it purely additive; the id-type mismatch
        # is flagged in docs/PHASE_C11_ORG_SERVICE_RESULT.md, not fixed
        # here.
    ]
