# Generated by Django 5.0.1 on 2025-11-24 10:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('soft_delete', 'Soft Delete'), ('restore', 'Restore')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('ticket', 'Ticket'), ('subticket', 'SubTicket'), ('user', 'User'), ('department', 'Department'), ('approval', 'Approval'), ('attachment', 'Attachment'), ('chat', 'Chat'), ('notification', 'Notification'), ('system', 'System')], db_index=True, max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.UUIDField(db_index=True)),
                ('old_state', models.JSONField(blank=True, default=dict, help_text='State before change')),
                ('new_state', models.JSONField(blank=True, default=dict, help_text='State after change')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Fields that changed')),
                ('performed_by_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for change')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', 'action_type'], name='audit_logs_categor_47a902_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_logs_model_n_656046_idx'), models.Index(fields=['performed_by_id'], name='audit_logs_perform_30f9f7_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'), models.Index(fields=['archived_at'], name='audit_logs_archive_2b0fbc_idx'), models.Index(fields=['category', 'timestamp'], name='audit_logs_categor_0633bd_idx')],
            },
        ),
    ]
