# Generated by Django 5.0.1 on 2026-07-29 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_tenant_employee_tenant_organization_tenant'),
        ('permissions', '0009_rbac_employee_role_and_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Null = no fixed end date', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='permissions.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='employees.tenant')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'permissions_subscription',
                'unique_together': {('tenant', 'service')},
            },
        ),
    ]
