# Generated by Django 5.0.1 on 2026-07-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_tenant_employee_tenant_organization_tenant'),
        ('permissions', '0010_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='role',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Catalog template (tenant=null, service_catalog set) cloned into per-tenant roles.'),
        ),
        migrations.AddField(
            model_name='role',
            name='service_catalog',
            field=models.ForeignKey(blank=True, help_text='Service this role is scoped to (FK). Null = legacy role predating the catalog.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='permissions.service'),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this role is scoped to. Null = legacy global/template role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='employees.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'service', 'tenant')},
        ),
    ]
