# Generated by Django 5.0.1 on 2026-07-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_tenant_employee_tenant_organization_tenant'),
        ('permissions', '0011_alter_role_unique_together_role_is_template_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('name', 'service'), name='uniq_role_name_service_global'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('name', 'service', 'tenant'), name='uniq_role_name_service_tenant'),
        ),
    ]
