# Generated by Django 5.0.1 on 2026-07-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0012_alter_role_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VmsRole',
        ),
    ]
