# Generated by Django 5.0.1 on 2026-07-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0013_delete_vmsrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HdmsRole',
        ),
    ]
