# Generated by Django 5.0.1 on 2026-08-03 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_nonstaffidentity_legacy_user_id'),
        ('employees', '0020_employee_legacy_user_id'),
        ('permissions', '0015_remove_sis_service_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermissionoverride',
            name='non_staff',
            field=models.ForeignKey(blank=True, help_text='Non-staff identity this override applies to (if non-staff, e.g. SMS student)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='authentication.nonstaffidentity'),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='non_staff',
            field=models.ForeignKey(blank=True, help_text='Non-staff identity this role is assigned to (if non-staff, e.g. SMS student)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='authentication.nonstaffidentity'),
        ),
        migrations.AddField(
            model_name='serviceaccess',
            name='non_staff',
            field=models.ForeignKey(blank=True, help_text='Non-staff identity who has access (if non-staff, e.g. SMS student)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_accesses', to='authentication.nonstaffidentity'),
        ),
        migrations.AlterField(
            model_name='employeepermissionoverride',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='employees.employee'),
        ),
    ]
