# Generated by Django 5.0.1 on 2025-11-24 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('head_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('active_tickets', models.IntegerField(default=0)),
                ('total_capacity', models.IntegerField(default=100)),
                ('queue_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'indexes': [models.Index(fields=['name'], name='departments_name_c59a45_idx'), models.Index(fields=['code'], name='departments_code_9f933a_idx'), models.Index(fields=['head_id'], name='departments_head_id_90aa66_idx'), models.Index(fields=['is_deleted'], name='departments_is_dele_50501c_idx')],
            },
        ),
    ]
