"""
Script: seed_certifications_from_sheet.py
Purpose: Read the Exam/Certification spreadsheet and create Certification records
         in the certification-service for students whose certifications were issued.

The Google Sheet has multiple tabs (e.g. DS11, CF01) each with:
  ID | STUDENT NAME | CONTACT NO | ATTENDANCE STATUS | PAPER STATUS | REMARKS | PAPER MARKS | CERTIFICATED ISSUE

Steps:
1. Download each sheet tab as CSV (using the tab GID), look for rows where CERTIFICATED ISSUE == 'Issue'
2. Use the Student ID to find the student's UUID from auth-service DB
3. Use the Student ID to find the Course from course-service DB (via course_code)
4. Create a Certification record in the certification-service DB

Usage (inside cert-service container):
  python seed_certifications_from_sheet.py

Dependencies:
  - student_mapping.json  (email -> UUID from auth-service seeding step)
  - course_mapping.json   (course_code -> course UUID from course-service)
  - The same Google Sheets ID / GIDs for the exam sheet

Place this script in: certification-service/
"""

import os
import django
import sys
import csv
import json
import uuid
import io
import re
import urllib.request
from datetime import datetime

# Setup Django Environment
sys.path.append('/app/seed_data')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'certification_service.settings')
django.setup()

from certifications.models import Certification

# =========================================================
# CONFIGURATION
# =========================================================
# All exam tabs found in the spreadsheet
# Tab name = course section (e.g. DS11 = Data Science section 1)
SHEET_TABS = [
    "AI11", "AI12",
    "CF01", "CF02", "CF03", "CF04", "CF05", "CF06", "CF07", "CF08", "CF09", "CF010",
    "CS11", "CS12",
    "DM11", "DM12",
    "DS11", "DS12",
    "GC11", "GC12", "GC13", "GC14",
    "GD11",
    "LE11", "LE12", "LE13", "LE14",
    "NS11",
    "VE11",
    "WD11", "WD12", "WD13", "WD14",
]
SPREADSHEET_ID = "1xjKEMq5N5PoG30AkDFBAgctiR20cdH30Ma4dpBrpIAI"

# Mapping files generated by previous steps
AUTH_MAPPING_PATH = '/app/student_mapping.json'     # email -> user_uuid
COURSE_MAPPING_PATH = '/app/course_mapping.json'    # course_code -> course_uuid (optional)

# =========================================================
# Helpers
# =========================================================
def fetch_csv_by_sheet_name(spreadsheet_id, sheet_name):
    """Download a Google Sheet tab as CSV using sheet name (no GID needed)."""
    url = f"https://docs.google.com/spreadsheets/d/{spreadsheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
    try:
        response = urllib.request.urlopen(url, timeout=30)
        content = response.read().decode('utf-8-sig')
        rows = list(csv.reader(io.StringIO(content)))
        if not rows:
            return []
        # Find header row (the one that has "ID" or "STUDENT NAME")
        header_row_idx = None
        for i, row in enumerate(rows):
            normalized = [c.strip().upper() for c in row]
            if 'ID' in normalized and 'STUDENT NAME' in normalized:
                header_row_idx = i
                break
        if header_row_idx is None:
            return []
        headers = [c.strip().upper() for c in rows[header_row_idx]]
        result = []
        for row in rows[header_row_idx + 1:]:
            if len(row) < len(headers):
                row += [''] * (len(headers) - len(row))
            result.append(dict(zip(headers, [c.strip() for c in row])))
        return result
    except Exception as e:
        print(f"  Error fetching sheet '{sheet_name}': {e}")
        return []

def extract_course_code(student_id_val):
    """Extract course code from student ID like AIT25-DS11-0872 -> DS1"""
    parts = student_id_val.split('-')
    if len(parts) >= 2:
        code_sec = parts[1]
        match = re.match(r'^([A-Za-z]+\d*)([1-9]\d*)$', code_sec)
        if match:
            return match.group(1)
        return code_sec
    return ''

def make_cert_number():
    """Generate a unique cert number."""
    return f"AIT-CERT-{uuid.uuid4().hex[:8].upper()}"

def make_verification_code():
    """Generate a unique verification code."""
    return uuid.uuid4().hex[:16].upper()

# =========================================================
# Main
# =========================================================
def seed_certifications():
    # Load student mapping (email -> user_uuid)
    student_by_email = {}
    if os.path.exists(AUTH_MAPPING_PATH):
        with open(AUTH_MAPPING_PATH, 'r') as f:
            student_by_email = json.load(f)
        print(f"Loaded {len(student_by_email)} student email->UUID mappings.")
    else:
        print(f"WARNING: No student_mapping.json at {AUTH_MAPPING_PATH}")

    # Load course mapping (course_code -> course_uuid) if available
    course_by_code = {}
    if os.path.exists(COURSE_MAPPING_PATH):
        with open(COURSE_MAPPING_PATH, 'r') as f:
            course_by_code = json.load(f)
        print(f"Loaded {len(course_by_code)} course code->UUID mappings.")
    else:
        print(f"Note: No course_mapping.json. Will only save course_code as text.")

    created = 0
    skipped = 0
    errors = 0

    for tab_name in SHEET_TABS:
        print(f"\nProcessing tab: {tab_name}...")
        rows = fetch_csv_by_sheet_name(SPREADSHEET_ID, tab_name)
        print(f"  Found {len(rows)} candidate rows.")

        for row in rows:
            student_id_val = row.get('ID', '').strip()
            student_name = row.get('STUDENT NAME', '').strip()
            cert_issue = row.get('CERTIFICATED ISSUE', '').strip().upper()
            paper_marks_raw = row.get('PAPER MARKS', '').strip()
            attendance_raw = row.get('ATTENDANCE STATUS', '').strip()
            paper_status = row.get('PAPER STATUS', '').strip()

            # Only process rows where certificate was issued
            if cert_issue != 'ISSUE':
                skipped += 1
                continue

            if not student_id_val or not student_name:
                skipped += 1
                continue

            # Extract course code from student ID
            course_code = extract_course_code(student_id_val)
            course_uuid = course_by_code.get(course_code)

            # Get student UUID via mapping (search by student_id_val in any email)
            # NOTE: Our mapping is email->UUID, student ID is not email.
            # We'll try to find this student via their student ID in auth-service
            # For now, try to find student_id_val pattern match in a student_id_to_uuid map if built
            # We will fall back to storing anonymously (without UUID) if not found
            student_uuid = None

            # Try to parse marks and attendance
            try:
                grade = float(paper_marks_raw) if paper_marks_raw and paper_marks_raw != '-' else None
            except ValueError:
                grade = None
            try:
                attendance_pct = float(attendance_raw) if attendance_raw else None
            except ValueError:
                attendance_pct = None

            # Check for existing cert with same student name + course_code to avoid duplicates
            if Certification.objects.filter(
                student_name=student_name,
                course_code=course_code
            ).exists():
                skipped += 1
                continue

            try:
                cert = Certification.objects.create(
                    student_id=student_uuid or student_id_val,
                    course_id=course_uuid or uuid.UUID('00000000-0000-0000-0000-000000000000'),
                    certificate_number=make_cert_number(),
                    verification_code=make_verification_code(),
                    student_name=student_name,
                    course_title=tab_name,
                    course_code=course_code,
                    grade=grade,
                    is_verified=True,
                    verified_at=datetime.now(),
                    institution_name='AIT Institute',
                )
                print(f"  ✓ Certificate issued for {student_name} ({student_id_val})")
                created += 1
            except Exception as e:
                print(f"  ✗ Error for {student_id_val}: {e}")
                errors += 1

    print(f"\nCertification seeding finished!")
    print(f"Certificates Issued (Created): {created}")
    print(f"Skipped (Not Issued / Duplicates): {skipped}")
    print(f"Errors: {errors}")

if __name__ == "__main__":
    seed_certifications()
