# Generated by Django 5.0.6 on 2026-03-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='batch_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='order_priority',
            field=models.IntegerField(default=0),
        ),
    ]
