# Generated by Django 5.0.6 on 2026-07-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentitem_lesson_module_usercontentprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='usercontentprogress',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
    ]
