# Generated by Django 5.0.1 on 2025-12-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_acknowledged_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_id',
            field=models.UUIDField(blank=True, help_text='Reference ID from file-service', null=True),
        ),
    ]
