# Generated by Django 5.0.1 on 2026-08-01 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_blacklistedtoken_token_to_textfield'),
        ('employees', '0019_tenant_employee_tenant_organization_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonStaffIdentity',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_type', models.CharField(choices=[('student', 'Student')], default='student', help_text='What kind of non-staff identity this is', max_length=20)),
                ('identity_code', models.CharField(help_text='Login identifier, analogous to Employee.employee_code / SuperAdmin.superadmin_code', max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, help_text="Free-form role label (e.g. SMS's 'student'). No role/permission catalog wiring yet — deferred to the phase that builds the actual login flow. See docs/PHASE_A2_STUDENT_IDENTITY_RESULT.md.", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(help_text='Tenant this identity belongs to (required — no HR chain to derive it from)', on_delete=django.db.models.deletion.PROTECT, related_name='non_staff_identities', to='employees.tenant')),
            ],
            options={
                'verbose_name': 'Non-Staff Identity',
                'verbose_name_plural': 'Non-Staff Identities',
                'db_table': 'auth_non_staff_identity',
            },
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='non_staff_identity',
            field=models.OneToOneField(blank=True, help_text='Non-staff identity these credentials belong to (if non-staff, e.g. SMS student)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='authentication.nonstaffidentity'),
        ),
    ]
