# Generated by Django 5.0.1 on 2026-08-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_nonstaffidentity_usercredentials_non_staff_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonstaffidentity',
            name='legacy_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Original SMS users_user.id (Phase B import key), null if not imported from SMS', null=True, unique=True),
        ),
    ]
