# Generated by Django 5.0.1 on 2026-08-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_nonstaffidentity_legacy_user_id'),
        ('employees', '0020_employee_legacy_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='non_staff_identity',
            field=models.ForeignKey(blank=True, help_text='Non-staff identity this token belongs to (e.g. SMS student) — Phase D-b1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='authentication.nonstaffidentity'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['non_staff_identity', 'is_revoked'], name='auth_refres_non_sta_046330_idx'),
        ),
    ]
