# Generated by Django 5.2.17 on 2026-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_last_class_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentevent',
            name='central_created_by_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentstatusrequest',
            name='central_org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentstatusrequest',
            name='central_requested_by_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentstatusrequest',
            name='central_reviewed_by_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentstatusrequest',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='central_org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='central_user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
