# Generated by Django 5.0.6 on 2026-01-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_assignment_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='seat_limit',
            field=models.IntegerField(default=30),
        ),
    ]
