# Generated by Django 5.0.6 on 2026-01-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_batch_seat_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistrationhistory',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('failed', 'Failed'), ('dropped', 'Dropped')], default='Enrolled', max_length=20),
        ),
    ]
