# Generated by Django 5.0.6 on 2026-02-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_scheduledclass_admission_open_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Advanced')], default=0),
        ),
    ]
