# Generated by Django 5.0.6 on 2026-02-13 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('content_id', models.UUIDField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_completions', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Content Completions',
                'unique_together': {('student_id', 'content_id')},
            },
        ),
    ]
