# Generated by Django 5.0.6 on 2026-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_name_alter_specialization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledclass',
            name='admission_open_date',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='course_end_date',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='course_start_date',
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='assistant_teacher_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='certificate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='certificate_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='exam_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='ramdan_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='total_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
