# Generated by Django 5.0.6 on 2026-03-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_scheduledclass_admission_open_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='course_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='course_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
