# Generated by Django 5.0.6 on 2026-03-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_scheduledclass_course_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
