# Generated by Django 5.0.6 on 2026-03-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledclass',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_scheduled_classes', to='courses.batch'),
        ),
        migrations.AlterField(
            model_name='scheduledclass',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_scheduled_classes', to='courses.room'),
        ),
    ]
