# Generated by Django 5.0.6 on 2026-04-03 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_scheduledclass_batch_alter_scheduledclass_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scheduled_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to='courses.scheduledclass'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('course', 'scheduled_class', 'student_id', 'date')},
        ),
    ]
