# Generated by Django 5.0.6 on 2026-04-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admission_open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='admission_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('coming_soon', 'Coming Soon')], default='coming_soon', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='course_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
