# Generated by Django 5.0.6 on 2026-04-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_admission_open_date_course_admission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='admission_open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
