# Generated by Django 5.0.6 on 2026-04-11 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_scheduledclass_admission_open_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('deposit_amount', models.IntegerField(default=5000)),
                ('bag_taken', models.BooleanField(default=True)),
                ('bag_fee', models.IntegerField(default=1000)),
                ('id_card_taken', models.BooleanField(default=True)),
                ('id_card_fee', models.IntegerField(default=500)),
                ('is_returned', models.BooleanField(default=False)),
                ('amount_returned', models.IntegerField(default=0, help_text='Amount dynamically calculated and stored at return time.')),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Student Deposits',
                'unique_together': {('student_id', 'course')},
            },
        ),
    ]
