# Generated by Django 5.0.6 on 2026-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_studentdeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistrationhistory',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('failed', 'Failed'), ('dropped', 'Dropped'), ('transferred', 'Transferred')], default='Enrolled', max_length=20),
        ),
    ]
