# Generated by Django 5.0.6 on 2026-04-13 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_courseregistrationhistory_status'),
    ]

    operations = [
        # 1. Remove Batch from Specialization and others (Fields that aren't in unique_together)
        migrations.RemoveField(
            model_name='specialization',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='batch',
        ),
        
        # 2. Add new fields to ScheduledClass
        migrations.AddField(
            model_name='scheduledclass',
            name='content_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='lab_room',
            field=models.CharField(blank=True, help_text='e.g. 1 | A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='strength_status',
            field=models.CharField(choices=[('seats_available', 'Seats Available'), ('full', 'Full'), ('filling_fast', 'Filling Fast')], default='seats_available', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        
        # 3. Add scheduled_class field to models that need it
        migrations.AddField(
            model_name='assignment',
            name='scheduled_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.scheduledclass'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='scheduled_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to='courses.scheduledclass'),
        ),
        
        # 4. NOW Alter unique_together (both fields 'batch' and 'scheduled_class' exist in the model state here)
        migrations.AlterUniqueTogether(
            name='courserating',
            unique_together={('student_id', 'course', 'scheduled_class')},
        ),
        
        # 5. NOW that the index is updated/dropped, we can safely remove the old field
        migrations.RemoveField(
            model_name='courserating',
            name='batch',
        ),
        
        # 6. Other adjustments
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Advanced')], default=1),
        ),
        
        # 7. Delete Batch model last
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
