# Generated by Django 5.0.6 on 2026-04-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_specialization_batch_remove_assignment_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
