# Generated by Django 5.0.6 on 2026-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_scheduledclass_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistrationhistory',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
