# Generated by Django 5.0.6 on 2026-04-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_courseregistrationhistory_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
    ]
