# Generated by Django 5.0.6 on 2026-04-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_scheduledclass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdeposit',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdeposit',
            name='deposit_amount',
            field=models.IntegerField(default=3000),
        ),
    ]
