# Generated by Django 5.0.6 on 2026-05-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_adminactionlog_course_deleted_at_course_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdeposit',
            name='bag_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentdeposit',
            name='bag_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdeposit',
            name='id_card_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentdeposit',
            name='id_card_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdeposit',
            name='is_waived',
            field=models.BooleanField(default=False),
        ),
    ]
