# Generated by Django 5.0.6 on 2026-05-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_studentdeposit_bag_paid_studentdeposit_bag_waived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistrationhistory',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('failed', 'Failed'), ('dropped', 'Dropped'), ('transferred', 'Transferred')], default='enrolled', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentcourseprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
