# Generated by Django 5.0.6 on 2026-05-19 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_courseregistrationhistory_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches where this course is offered', related_name='courses', to='courses.branch'),
        ),
        migrations.AddField(
            model_name='courseregistrationhistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.branch'),
        ),
        migrations.AddField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='courses.branch'),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='courses.branch'),
        ),
        migrations.AddField(
            model_name='studentdeposit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='courses.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('branch', 'name')},
        ),
    ]
