# Generated by Django 5.0.6 on 2026-05-20 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_branch_alter_room_name_course_branches_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('course', 'Per Course (all sections)'), ('scheduled_class', 'Per Time Slot (section-specific)')], default='course', max_length=20)),
                ('monthly_maintenance_fee', models.IntegerField(default=0, help_text='Monthly recurring fee')),
                ('one_time_fee', models.IntegerField(default=0, help_text='One-time course fee')),
                ('payment_plan', models.CharField(choices=[('monthly', 'Monthly'), ('one_time', 'One Time')], default='monthly', max_length=20)),
                ('due_day_of_month', models.IntegerField(default=10, help_text='Day of month when fee is due (1-28)')),
                ('require_deposit_paid', models.BooleanField(default=True, help_text='Only charge students who have paid deposit')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(help_text='Fee applies from this date')),
                ('effective_to', models.DateField(blank=True, help_text='Fee stops applying after this date', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='courses.course')),
                ('scheduled_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='courses.scheduledclass')),
            ],
            options={
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['course__name', 'scope'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('fee_month', models.DateField(help_text='First day of the fee month')),
                ('amount_due', models.IntegerField()),
                ('amount_paid', models.IntegerField(default=0)),
                ('outstanding_balance', models.IntegerField(default=0)),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('collected_by_id', models.UUIDField(blank=True, null=True)),
                ('collected_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_records', to='courses.course')),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_records', to='courses.feestructure')),
                ('scheduled_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_fee_records', to='courses.scheduledclass')),
            ],
            options={
                'verbose_name_plural': 'Student Fee Records',
                'ordering': ['-fee_month', 'payment_status'],
                'unique_together': {('student_id', 'course', 'scheduled_class', 'fee_month')},
            },
        ),
        migrations.CreateModel(
            name='FeePaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('online', 'Online Payment'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('received_by_id', models.UUIDField(blank=True, null=True)),
                ('received_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='courses.studentfeerecord')),
            ],
            options={
                'verbose_name_plural': 'Fee Payment Transactions',
                'ordering': ['-received_at'],
            },
        ),
    ]
