# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_feestructure_studentfeerecord_feepaymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdeposit',
            name='certificate_taken',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentdeposit',
            name='certificate_fee',
            field=models.IntegerField(default=200, help_text='Certificate issuance fee'),
        ),
        migrations.AddField(
            model_name='studentdeposit',
            name='certificate_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentdeposit',
            name='certificate_waived',
            field=models.BooleanField(default=False),
        ),
    ]
