# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_studentdeposit_certificate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='additional_teacher_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
