# Generated by Django 5.0.6 on 2026-06-02 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_scheduledclass_additional_teacher_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdeposit',
            name='bag_fee',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='studentdeposit',
            name='id_card_fee',
            field=models.IntegerField(default=200),
        ),
        migrations.CreateModel(
            name='AttendanceContactLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contacted_by_id', models.UUIDField()),
                ('contacted_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Phone Call'), ('sms', 'SMS'), ('email', 'Email'), ('in_person', 'In Person')], default='whatsapp', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='courses.attendance')),
            ],
            options={
                'verbose_name_plural': 'Attendance Contact Logs',
                'ordering': ['-contacted_at'],
            },
        ),
    ]
