# Generated by Django 5.0.6 on 2026-07-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_fee_record_fields_and_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=6, help_text='Duration in months'),
        ),
        migrations.AlterField(
            model_name='studentfeerecord',
            name='fee_month',
            field=models.DateField(help_text='First day of the fee month (for full payment, the first month of coverage)'),
        ),
    ]
