# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdeposit',
            name='deposit_paid',
            field=models.BooleanField(default=True, help_text='Whether the initial deposit itself has been paid (separate from is_waived)'),
        ),
    ]
