# Generated by Django 5.0.6 on 2026-07-14 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_studentdeposit_deposit_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Holidays',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ZKTecoDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=4370)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('campus_id', models.UUIDField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ZKTeco Devices',
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('scheduled_class', 'date')},
        ),
        migrations.AddField(
            model_name='assignment',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='absent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='present_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reviewed_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='submitted_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='update_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contentcompletion',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='courserating',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='courseregistrationhistory',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='feepaymenttransaction',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='studentcourseprogress',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='studentdeposit',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='studentfeerecord',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='studentwarning',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(default='attendance', max_length=50)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('submit', 'Submit'), ('review', 'Review'), ('approve', 'Approve'), ('reopen', 'Reopen'), ('delete', 'Delete')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('user_id', models.UUIDField()),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['feature', 'action'], name='courses_att_feature_323053_idx'), models.Index(fields=['entity_type', 'entity_id'], name='courses_att_entity__861180_idx'), models.Index(fields=['user_id', 'timestamp'], name='courses_att_user_id_340390_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceBackfillPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_to_id', models.UUIDField()),
                ('granted_by_id', models.UUIDField()),
                ('deadline', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_permissions', to='courses.scheduledclass')),
            ],
            options={
                'verbose_name_plural': 'Attendance Backfill Permissions',
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('campus_id', models.UUIDField(blank=True, null=True)),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave'), ('half_day', 'Half Day'), ('not_marked', 'Not Marked')], default='not_marked', max_length=20)),
                ('late_minutes', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('biometric', 'Biometric'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('marked_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Staff Attendances',
                'unique_together': {('user_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('day_of_week', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Weekends',
                'unique_together': {('organization_id', 'day_of_week')},
            },
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student_id',
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave'), ('excused', 'Excused')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='courses.attendance')),
            ],
            options={
                'verbose_name_plural': 'Student Attendances',
                'unique_together': {('student_id', 'attendance')},
            },
        ),
        migrations.CreateModel(
            name='ZKTecoEmployeeMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_user_id', models.CharField(max_length=50)),
                ('user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='courses.zktecodevice')),
            ],
            options={
                'verbose_name_plural': 'ZKTeco Employee Mappings',
                'unique_together': {('device', 'device_user_id')},
            },
        ),
    ]
