# Generated by Django 5.0.6 on 2026-07-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_add_multitenancy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='campus_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Campus', null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='campus_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Campus', null=True),
        ),
    ]
