# Generated by Django 5.2.17 on 2026-08-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0005_backfill_coordinator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='central_user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
