--
-- PostgreSQL database dump
--

\restrict 2VXy61MFKZER1RbLlsdzHhsrEqFCwiJMe3pccgNqj3FbLgFYS5hLbOCIhmcgd52

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campus_campus; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campus_campus (
    id integer NOT NULL,
    campus_photo character varying(100),
    campus_id character varying(50) NOT NULL,
    campus_code character varying(50),
    campus_name character varying(255) NOT NULL,
    campus_type character varying(20) NOT NULL,
    governing_body character varying(255),
    accreditation character varying(255),
    instruction_language character varying(255),
    academic_year_start date,
    academic_year_end date,
    established_year integer,
    registration_number character varying(100),
    address_full text NOT NULL,
    postal_code character varying(20) NOT NULL,
    city character varying(100) NOT NULL,
    district character varying(100),
    primary_phone character varying(20) NOT NULL,
    secondary_phone character varying(20),
    official_email character varying(254) NOT NULL,
    campus_head_name character varying(255) NOT NULL,
    campus_head_phone character varying(50),
    campus_head_email character varying(254),
    student_capacity integer NOT NULL,
    academic_year_start_month character varying(20),
    academic_year_end_month character varying(20),
    shift_available character varying(20) NOT NULL,
    grades_available text,
    grades_offered text,
    total_rooms integer NOT NULL,
    total_classrooms integer NOT NULL,
    total_staff_rooms integer NOT NULL,
    has_computer_lab boolean NOT NULL,
    has_science_lab boolean NOT NULL,
    has_biology_lab boolean NOT NULL,
    has_chemistry_lab boolean NOT NULL,
    has_physics_lab boolean NOT NULL,
    library_available boolean NOT NULL,
    power_backup boolean NOT NULL,
    internet_available boolean NOT NULL,
    teacher_transport boolean NOT NULL,
    student_transport boolean NOT NULL,
    canteen_facility boolean NOT NULL,
    meal_program boolean NOT NULL,
    status character varying(20) NOT NULL,
    sports_available text,
    grades_data jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_draft boolean NOT NULL,
    organization_id bigint,
    CONSTRAINT campus_campus_established_year_check CHECK ((established_year >= 0)),
    CONSTRAINT campus_campus_student_capacity_check CHECK ((student_capacity >= 0)),
    CONSTRAINT campus_campus_total_classrooms_check CHECK ((total_classrooms >= 0)),
    CONSTRAINT campus_campus_total_rooms_check CHECK ((total_rooms >= 0)),
    CONSTRAINT campus_campus_total_staff_rooms_check CHECK ((total_staff_rooms >= 0))
);


--
-- Name: campus_campus_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.campus_campus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campus_campus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: global_counters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.global_counters (
    id bigint NOT NULL,
    key character varying(50) NOT NULL,
    value integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    organization_id bigint,
    CONSTRAINT global_counters_value_check CHECK ((value >= 0))
);


--
-- Name: global_counters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.global_counters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.global_counters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_organization; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_organization (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    subdomain character varying(100),
    max_users integer NOT NULL,
    max_students integer NOT NULL,
    max_campuses integer NOT NULL,
    is_active boolean NOT NULL,
    enabled_features jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    plan_id bigint,
    code_prefix character varying(6),
    code_pattern character varying(30) DEFAULT ''::character varying,
    student_id_pattern character varying(30) DEFAULT 'STD_PREFIX_YY_SEQ5'::character varying,
    payment_status character varying(10) NOT NULL,
    CONSTRAINT users_organization_max_campuses_check CHECK ((max_campuses >= 0)),
    CONSTRAINT users_organization_max_students_check CHECK ((max_students >= 0)),
    CONSTRAINT users_organization_max_users_check CHECK ((max_users >= 0))
);


--
-- Name: users_organization_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_organization ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_organization_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_password_change_otp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_password_change_otp (
    id bigint NOT NULL,
    otp_code character varying(6) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_used boolean NOT NULL,
    session_token character varying(64),
    user_id bigint NOT NULL
);


--
-- Name: users_password_change_otp_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_password_change_otp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_password_change_otp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_role_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_role_permission (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    permission_codename character varying(100) NOT NULL,
    is_allowed boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id bigint
);


--
-- Name: users_role_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_role_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_role_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_subscription_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_subscription_plan (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    max_users integer NOT NULL,
    max_students integer NOT NULL,
    max_campuses integer NOT NULL,
    description text,
    base_price numeric(10,2) NOT NULL,
    price_per_student numeric(10,2) NOT NULL,
    price_per_user numeric(10,2) NOT NULL,
    is_enterprise boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    CONSTRAINT users_subscription_plan_max_campuses_check CHECK ((max_campuses >= 0)),
    CONSTRAINT users_subscription_plan_max_students_check CHECK ((max_students >= 0)),
    CONSTRAINT users_subscription_plan_max_users_check CHECK ((max_users >= 0))
);


--
-- Name: users_subscription_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_subscription_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_subscription_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_system_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_system_version (
    id bigint NOT NULL,
    version character varying(50) NOT NULL,
    build integer NOT NULL,
    release_notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    released_by_id bigint,
    CONSTRAINT users_system_version_build_check CHECK ((build >= 0))
);


--
-- Name: users_system_version_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_system_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_system_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    username character varying(150) NOT NULL,
    is_org_admin boolean NOT NULL,
    role character varying(20) NOT NULL,
    phone_number character varying(20),
    biometric_id character varying(50),
    photo character varying(100),
    is_verified boolean NOT NULL,
    last_login_ip inet,
    has_changed_default_password boolean NOT NULL,
    token_version integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    campus_id integer,
    organization_id bigint,
    is_deleted boolean NOT NULL,
    CONSTRAINT users_user_token_version_check CHECK ((token_version >= 0))
);


--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Blacklisted Token	6	add_blacklistedtoken
22	Can change Blacklisted Token	6	change_blacklistedtoken
23	Can delete Blacklisted Token	6	delete_blacklistedtoken
24	Can view Blacklisted Token	6	view_blacklistedtoken
25	Can add Outstanding Token	7	add_outstandingtoken
26	Can change Outstanding Token	7	change_outstandingtoken
27	Can delete Outstanding Token	7	delete_outstandingtoken
28	Can view Outstanding Token	7	view_outstandingtoken
29	Can add User	8	add_user
30	Can change User	8	change_user
31	Can delete User	8	delete_user
32	Can view User	8	view_user
33	Can add Organization	9	add_organization
34	Can change Organization	9	change_organization
35	Can delete Organization	9	delete_organization
36	Can view Organization	9	view_organization
37	Can add Password Change OTP	10	add_passwordchangeotp
38	Can change Password Change OTP	10	change_passwordchangeotp
39	Can delete Password Change OTP	10	delete_passwordchangeotp
40	Can view Password Change OTP	10	view_passwordchangeotp
41	Can add Subscription Plan	11	add_subscriptionplan
42	Can change Subscription Plan	11	change_subscriptionplan
43	Can delete Subscription Plan	11	delete_subscriptionplan
44	Can view Subscription Plan	11	view_subscriptionplan
45	Can add Role Permission	12	add_rolepermission
46	Can change Role Permission	12	change_rolepermission
47	Can delete Role Permission	12	delete_rolepermission
48	Can view Role Permission	12	view_rolepermission
49	Can add System Version	13	add_systemversion
50	Can change System Version	13	change_systemversion
51	Can delete System Version	13	delete_systemversion
52	Can view System Version	13	view_systemversion
53	Can add campus	14	add_campus
54	Can change campus	14	change_campus
55	Can delete campus	14	delete_campus
56	Can view campus	14	view_campus
57	Can add global counter	15	add_globalcounter
58	Can change global counter	15	change_globalcounter
59	Can delete global counter	15	delete_globalcounter
60	Can view global counter	15	view_globalcounter
\.


--
-- Data for Name: campus_campus; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.campus_campus (id, campus_photo, campus_id, campus_code, campus_name, campus_type, governing_body, accreditation, instruction_language, academic_year_start, academic_year_end, established_year, registration_number, address_full, postal_code, city, district, primary_phone, secondary_phone, official_email, campus_head_name, campus_head_phone, campus_head_email, student_capacity, academic_year_start_month, academic_year_end_month, shift_available, grades_available, grades_offered, total_rooms, total_classrooms, total_staff_rooms, has_computer_lab, has_science_lab, has_biology_lab, has_chemistry_lab, has_physics_lab, library_available, power_backup, internet_available, teacher_transport, student_transport, canteen_facility, meal_program, status, sports_available, grades_data, created_at, updated_at, is_draft, organization_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	token_blacklist	blacklistedtoken
7	token_blacklist	outstandingtoken
8	users	user
9	users	organization
10	users	passwordchangeotp
11	users	subscriptionplan
12	users	rolepermission
13	users	systemversion
14	campus	campus
15	services	globalcounter
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	campus	0001_initial	2026-08-08 05:00:43.686554+00
2	contenttypes	0001_initial	2026-08-08 05:00:43.697353+00
3	contenttypes	0002_remove_content_type_name	2026-08-08 05:00:43.703981+00
4	auth	0001_initial	2026-08-08 05:00:43.751099+00
5	auth	0002_alter_permission_name_max_length	2026-08-08 05:00:43.755204+00
6	auth	0003_alter_user_email_max_length	2026-08-08 05:00:43.759876+00
7	auth	0004_alter_user_username_opts	2026-08-08 05:00:43.763797+00
8	auth	0005_alter_user_last_login_null	2026-08-08 05:00:43.767355+00
9	auth	0006_require_contenttypes_0002	2026-08-08 05:00:43.769013+00
10	auth	0007_alter_validators_add_error_messages	2026-08-08 05:00:43.772534+00
11	auth	0008_alter_user_username_max_length	2026-08-08 05:00:43.776209+00
12	auth	0009_alter_user_last_name_max_length	2026-08-08 05:00:43.780027+00
13	auth	0010_alter_group_name_max_length	2026-08-08 05:00:43.786643+00
14	auth	0011_update_proxy_permissions	2026-08-08 05:00:43.791885+00
15	auth	0012_alter_user_first_name_max_length	2026-08-08 05:00:43.795467+00
16	users	0001_initial	2026-08-08 05:00:43.961739+00
17	admin	0001_initial	2026-08-08 05:00:43.988355+00
18	admin	0002_logentry_remove_auto_add	2026-08-08 05:00:43.996359+00
19	admin	0003_logentry_add_action_flag_choices	2026-08-08 05:00:44.004293+00
20	campus	0002_initial	2026-08-08 05:00:44.027004+00
21	services	0001_initial	2026-08-08 05:00:44.033402+00
22	services	0002_initial	2026-08-08 05:00:44.056791+00
23	sessions	0001_initial	2026-08-08 05:00:44.073176+00
24	token_blacklist	0001_initial	2026-08-08 05:00:44.117607+00
25	token_blacklist	0002_outstandingtoken_jti_hex	2026-08-08 05:00:44.126823+00
26	token_blacklist	0003_auto_20171017_2007	2026-08-08 05:00:44.138629+00
27	token_blacklist	0004_auto_20171017_2013	2026-08-08 05:00:44.153207+00
28	token_blacklist	0005_remove_outstandingtoken_jti	2026-08-08 05:00:44.163554+00
29	token_blacklist	0006_auto_20171017_2113	2026-08-08 05:00:44.174938+00
30	token_blacklist	0007_auto_20171017_2214	2026-08-08 05:00:44.20769+00
31	token_blacklist	0008_migrate_to_bigautofield	2026-08-08 05:00:44.265721+00
32	token_blacklist	0010_fix_migrate_to_bigautofield	2026-08-08 05:00:44.279452+00
33	token_blacklist	0011_linearizes_history	2026-08-08 05:00:44.28156+00
34	token_blacklist	0012_alter_outstandingtoken_user	2026-08-08 05:00:44.295894+00
35	token_blacklist	0013_alter_blacklistedtoken_options_and_more	2026-08-08 05:00:44.333687+00
36	users	0002_add_org_code_prefix_pattern	2026-08-08 05:00:44.364108+00
37	users	0003_add_is_deleted_to_user	2026-08-08 05:00:44.374462+00
38	users	0004_add_student_id_pattern	2026-08-08 05:00:44.38641+00
39	users	0005_org_payment_status	2026-08-08 05:00:44.398931+00
40	users	0006_org_pattern_nullable	2026-08-08 05:00:44.402497+00
41	users	0007_alter_organization_code_pattern	2026-08-08 05:00:44.411108+00
42	users	0008_add_system_version	2026-08-08 05:00:44.433765+00
43	users	0010_alter_rolepermission_permission_codename	2026-08-08 05:00:44.441153+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: global_counters; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.global_counters (id, key, value, updated_at, created_at, organization_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
\.


--
-- Data for Name: users_organization; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_organization (id, name, subdomain, max_users, max_students, max_campuses, is_active, enabled_features, created_at, updated_at, created_by_id, plan_id, code_prefix, code_pattern, student_id_pattern, payment_status) FROM stdin;
6	R2 Verify Organization	\N	50	1000	3	t	{"academic": true, "students": true, "analytics": true, "attendance": true, "management": true, "administration": true}	2026-08-08 05:19:43.783771+00	2026-08-08 05:19:43.784054+00	\N	\N	R2VOA	PREFIX_YY_ROLE_SEQ4	STD_PREFIX_YY_SEQ5	paid
\.


--
-- Data for Name: users_password_change_otp; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_password_change_otp (id, otp_code, created_at, expires_at, is_used, session_token, user_id) FROM stdin;
\.


--
-- Data for Name: users_role_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_role_permission (id, role, permission_codename, is_allowed, updated_at, organization_id) FROM stdin;
1	superadmin	view_dashboard	t	2026-08-08 05:19:43.794975+00	6
2	superadmin	view_students	t	2026-08-08 05:19:43.797547+00	6
3	superadmin	add_student	t	2026-08-08 05:19:43.799405+00	6
4	superadmin	edit_student	t	2026-08-08 05:19:43.80095+00	6
5	superadmin	view_teachers	t	2026-08-08 05:19:43.802489+00	6
6	superadmin	add_teacher	t	2026-08-08 05:19:43.805251+00	6
7	superadmin	view_campus	t	2026-08-08 05:19:43.80739+00	6
8	superadmin	add_campus	t	2026-08-08 05:19:43.80906+00	6
9	superadmin	view_principals	t	2026-08-08 05:19:43.810556+00	6
10	superadmin	add_principal	t	2026-08-08 05:19:43.81202+00	6
11	superadmin	view_coordinators	t	2026-08-08 05:19:43.813345+00	6
12	superadmin	add_coordinator	t	2026-08-08 05:19:43.814801+00	6
13	superadmin	view_attendance	t	2026-08-08 05:19:43.816157+00	6
14	superadmin	mark_attendance	t	2026-08-08 05:19:43.817553+00	6
15	superadmin	approve_attendance	t	2026-08-08 05:19:43.818902+00	6
16	superadmin	view_results	t	2026-08-08 05:19:43.820082+00	6
17	superadmin	approve_results	t	2026-08-08 05:19:43.821536+00	6
18	superadmin	bulk_import_results	t	2026-08-08 05:19:43.82274+00	6
19	superadmin	edit_results	t	2026-08-08 05:19:43.823964+00	6
20	superadmin	view_transfers	t	2026-08-08 05:19:43.825736+00	6
21	superadmin	view_timetable	t	2026-08-08 05:19:43.82779+00	6
22	superadmin	view_requests	t	2026-08-08 05:19:43.829666+00	6
23	superadmin	view_promotions	t	2026-08-08 05:19:43.831222+00	6
24	superadmin	view_subjects	t	2026-08-08 05:19:43.833144+00	6
25	superadmin	view_grade_distribution_chart	t	2026-08-08 05:19:43.835086+00	6
26	superadmin	view_gender_distribution_chart	t	2026-08-08 05:19:43.836978+00	6
27	superadmin	view_mother_tongue_chart	t	2026-08-08 05:19:43.838393+00	6
28	superadmin	view_religion_chart	t	2026-08-08 05:19:43.83975+00	6
29	superadmin	view_enrollment_trend_chart	t	2026-08-08 05:19:43.841881+00	6
30	superadmin	view_age_distribution_chart	t	2026-08-08 05:19:43.843268+00	6
31	superadmin	view_weekly_attendance_chart	t	2026-08-08 05:19:43.844578+00	6
32	superadmin	view_zakat_status_chart	t	2026-08-08 05:19:43.8461+00	6
33	superadmin	view_house_ownership_chart	t	2026-08-08 05:19:43.847484+00	6
34	superadmin	view_network_performance_chart	t	2026-08-08 05:19:43.848809+00	6
35	superadmin	view_total_students_kpi	t	2026-08-08 05:19:43.850165+00	6
36	superadmin	view_total_teachers_kpi	t	2026-08-08 05:19:43.851711+00	6
37	superadmin	view_teacher_student_ratio_kpi	t	2026-08-08 05:19:43.853045+00	6
38	superadmin	view_avg_attendance_kpi	t	2026-08-08 05:19:43.854349+00	6
39	superadmin	view_fees	t	2026-08-08 05:19:43.855653+00	6
40	superadmin	manage_fees	t	2026-08-08 05:19:43.857177+00	6
41	superadmin	view_admin_dashboard	t	2026-08-08 05:19:43.85844+00	6
42	superadmin	view_teacher_dashboard	t	2026-08-08 05:19:43.859613+00	6
43	superadmin	view_coordinator_dashboard	t	2026-08-08 05:19:43.860905+00	6
44	superadmin	view_principal_dashboard	t	2026-08-08 05:19:43.862039+00	6
45	superadmin	view_student_dashboard	t	2026-08-08 05:19:43.863181+00	6
46	superadmin	view_superadmin_dashboard	t	2026-08-08 05:19:43.864314+00	6
47	superadmin	manage_permissions	t	2026-08-08 05:19:43.865414+00	6
48	superadmin	manage_forms	t	2026-08-08 05:19:43.866522+00	6
49	org_admin	view_dashboard	t	2026-08-08 05:19:43.867652+00	6
50	org_admin	view_students	t	2026-08-08 05:19:43.868958+00	6
51	org_admin	add_student	t	2026-08-08 05:19:43.870216+00	6
52	org_admin	edit_student	t	2026-08-08 05:19:43.871495+00	6
53	org_admin	view_teachers	t	2026-08-08 05:19:43.872685+00	6
54	org_admin	add_teacher	t	2026-08-08 05:19:43.874332+00	6
55	org_admin	view_campus	t	2026-08-08 05:19:43.876398+00	6
56	org_admin	add_campus	t	2026-08-08 05:19:43.877872+00	6
57	org_admin	view_principals	t	2026-08-08 05:19:43.879158+00	6
58	org_admin	add_principal	t	2026-08-08 05:19:43.880299+00	6
59	org_admin	view_coordinators	t	2026-08-08 05:19:43.881744+00	6
60	org_admin	add_coordinator	t	2026-08-08 05:19:43.883094+00	6
61	org_admin	view_attendance	t	2026-08-08 05:19:43.884431+00	6
62	org_admin	mark_attendance	t	2026-08-08 05:19:43.885769+00	6
63	org_admin	approve_attendance	t	2026-08-08 05:19:43.887095+00	6
64	org_admin	view_results	t	2026-08-08 05:19:43.888441+00	6
65	org_admin	approve_results	t	2026-08-08 05:19:43.889776+00	6
66	org_admin	view_transfers	t	2026-08-08 05:19:43.891145+00	6
67	org_admin	view_timetable	t	2026-08-08 05:19:43.892473+00	6
68	org_admin	view_requests	t	2026-08-08 05:19:43.893888+00	6
69	org_admin	view_promotions	t	2026-08-08 05:19:43.895174+00	6
70	org_admin	view_subjects	t	2026-08-08 05:19:43.896609+00	6
71	org_admin	view_grade_distribution_chart	t	2026-08-08 05:19:43.897955+00	6
72	org_admin	view_gender_distribution_chart	t	2026-08-08 05:19:43.899234+00	6
73	org_admin	view_mother_tongue_chart	t	2026-08-08 05:19:43.900482+00	6
74	org_admin	view_religion_chart	t	2026-08-08 05:19:43.901811+00	6
75	org_admin	view_enrollment_trend_chart	t	2026-08-08 05:19:43.90307+00	6
76	org_admin	view_age_distribution_chart	t	2026-08-08 05:19:43.904307+00	6
77	org_admin	view_weekly_attendance_chart	t	2026-08-08 05:19:43.905617+00	6
78	org_admin	view_zakat_status_chart	t	2026-08-08 05:19:43.906806+00	6
79	org_admin	view_house_ownership_chart	t	2026-08-08 05:19:43.908082+00	6
80	org_admin	view_network_performance_chart	t	2026-08-08 05:19:43.909228+00	6
81	org_admin	view_total_students_kpi	t	2026-08-08 05:19:43.910449+00	6
82	org_admin	view_total_teachers_kpi	t	2026-08-08 05:19:43.911598+00	6
83	org_admin	view_teacher_student_ratio_kpi	t	2026-08-08 05:19:43.912825+00	6
84	org_admin	view_avg_attendance_kpi	t	2026-08-08 05:19:43.914107+00	6
85	org_admin	view_fees	t	2026-08-08 05:19:43.915407+00	6
86	org_admin	manage_fees	t	2026-08-08 05:19:43.916726+00	6
87	org_admin	view_admin_dashboard	t	2026-08-08 05:19:43.91806+00	6
88	org_admin	view_teacher_dashboard	t	2026-08-08 05:19:43.919419+00	6
89	org_admin	view_coordinator_dashboard	t	2026-08-08 05:19:43.920694+00	6
90	org_admin	view_principal_dashboard	t	2026-08-08 05:19:43.921951+00	6
91	org_admin	view_student_dashboard	t	2026-08-08 05:19:43.923241+00	6
92	org_admin	manage_permissions	t	2026-08-08 05:19:43.924556+00	6
93	org_admin	manage_forms	t	2026-08-08 05:19:43.925822+00	6
94	principal	view_dashboard	t	2026-08-08 05:19:43.927113+00	6
95	principal	view_students	t	2026-08-08 05:19:43.928368+00	6
96	principal	add_student	t	2026-08-08 05:19:43.929898+00	6
97	principal	edit_student	t	2026-08-08 05:19:43.931159+00	6
98	principal	view_teachers	t	2026-08-08 05:19:43.93241+00	6
99	principal	add_teacher	t	2026-08-08 05:19:43.933801+00	6
100	principal	view_campus	t	2026-08-08 05:19:43.935037+00	6
101	principal	add_campus	t	2026-08-08 05:19:43.936267+00	6
102	principal	view_principals	f	2026-08-08 05:19:43.937542+00	6
103	principal	add_principal	f	2026-08-08 05:19:43.938795+00	6
104	principal	view_coordinators	t	2026-08-08 05:19:43.940087+00	6
105	principal	add_coordinator	t	2026-08-08 05:19:43.94136+00	6
106	principal	view_attendance	t	2026-08-08 05:19:43.942813+00	6
107	principal	mark_attendance	f	2026-08-08 05:19:43.944314+00	6
108	principal	approve_attendance	t	2026-08-08 05:19:43.945735+00	6
109	principal	view_results	t	2026-08-08 05:19:43.946912+00	6
110	principal	approve_results	t	2026-08-08 05:19:43.948011+00	6
111	principal	bulk_import_results	t	2026-08-08 05:19:43.949545+00	6
112	principal	edit_results	t	2026-08-08 05:19:43.950942+00	6
113	principal	view_transfers	t	2026-08-08 05:19:43.952192+00	6
114	principal	view_timetable	t	2026-08-08 05:19:43.9539+00	6
115	principal	view_requests	t	2026-08-08 05:19:43.955803+00	6
116	principal	view_promotions	t	2026-08-08 05:19:43.95738+00	6
117	principal	view_subjects	t	2026-08-08 05:19:43.959125+00	6
118	principal	view_fees	t	2026-08-08 05:19:43.961084+00	6
119	principal	manage_fees	t	2026-08-08 05:19:43.962543+00	6
120	principal	view_grade_distribution_chart	t	2026-08-08 05:19:43.963787+00	6
121	principal	view_gender_distribution_chart	t	2026-08-08 05:19:43.965367+00	6
122	principal	view_mother_tongue_chart	t	2026-08-08 05:19:43.967164+00	6
123	principal	view_religion_chart	t	2026-08-08 05:19:43.969029+00	6
124	principal	view_enrollment_trend_chart	t	2026-08-08 05:19:43.970643+00	6
125	principal	view_age_distribution_chart	t	2026-08-08 05:19:43.972137+00	6
126	principal	view_weekly_attendance_chart	t	2026-08-08 05:19:43.973487+00	6
127	principal	view_zakat_status_chart	t	2026-08-08 05:19:43.975676+00	6
128	principal	view_house_ownership_chart	t	2026-08-08 05:19:43.977187+00	6
129	principal	view_network_performance_chart	t	2026-08-08 05:19:43.979321+00	6
130	principal	view_total_students_kpi	t	2026-08-08 05:19:43.980693+00	6
131	principal	view_total_teachers_kpi	t	2026-08-08 05:19:43.982396+00	6
132	principal	view_teacher_student_ratio_kpi	t	2026-08-08 05:19:43.98347+00	6
133	principal	view_avg_attendance_kpi	t	2026-08-08 05:19:43.984613+00	6
134	principal	view_principal_dashboard	t	2026-08-08 05:19:43.985695+00	6
135	principal	manage_permissions	f	2026-08-08 05:19:43.98679+00	6
136	principal	manage_forms	f	2026-08-08 05:19:43.988068+00	6
137	coordinator	view_dashboard	t	2026-08-08 05:19:43.989322+00	6
138	coordinator	view_students	t	2026-08-08 05:19:43.990598+00	6
139	coordinator	add_student	t	2026-08-08 05:19:43.991962+00	6
140	coordinator	edit_student	t	2026-08-08 05:19:43.99328+00	6
141	coordinator	view_teachers	t	2026-08-08 05:19:43.994631+00	6
142	coordinator	add_teacher	f	2026-08-08 05:19:43.995849+00	6
143	coordinator	view_campus	f	2026-08-08 05:19:43.997145+00	6
144	coordinator	add_campus	f	2026-08-08 05:19:43.998409+00	6
145	coordinator	view_principals	f	2026-08-08 05:19:43.999609+00	6
146	coordinator	add_principal	f	2026-08-08 05:19:44.000903+00	6
147	coordinator	view_coordinators	f	2026-08-08 05:19:44.0021+00	6
148	coordinator	add_coordinator	f	2026-08-08 05:19:44.003276+00	6
149	coordinator	view_attendance	t	2026-08-08 05:19:44.004558+00	6
150	coordinator	mark_attendance	f	2026-08-08 05:19:44.005782+00	6
151	coordinator	approve_attendance	t	2026-08-08 05:19:44.007163+00	6
152	coordinator	view_results	t	2026-08-08 05:19:44.010161+00	6
153	coordinator	approve_results	t	2026-08-08 05:19:44.011619+00	6
154	coordinator	bulk_import_results	t	2026-08-08 05:19:44.013025+00	6
155	coordinator	edit_results	t	2026-08-08 05:19:44.014377+00	6
156	coordinator	view_transfers	t	2026-08-08 05:19:44.015845+00	6
157	coordinator	view_timetable	t	2026-08-08 05:19:44.017172+00	6
158	coordinator	view_requests	t	2026-08-08 05:19:44.018412+00	6
159	coordinator	view_promotions	f	2026-08-08 05:19:44.019877+00	6
160	coordinator	view_subjects	t	2026-08-08 05:19:44.021191+00	6
161	coordinator	view_fees	t	2026-08-08 05:19:44.022515+00	6
162	coordinator	manage_fees	f	2026-08-08 05:19:44.023794+00	6
163	coordinator	view_grade_distribution_chart	t	2026-08-08 05:19:44.024854+00	6
164	coordinator	view_gender_distribution_chart	t	2026-08-08 05:19:44.025869+00	6
165	coordinator	view_mother_tongue_chart	t	2026-08-08 05:19:44.027041+00	6
166	coordinator	view_religion_chart	t	2026-08-08 05:19:44.028235+00	6
167	coordinator	view_enrollment_trend_chart	t	2026-08-08 05:19:44.029495+00	6
168	coordinator	view_age_distribution_chart	t	2026-08-08 05:19:44.030474+00	6
169	coordinator	view_weekly_attendance_chart	t	2026-08-08 05:19:44.031427+00	6
170	coordinator	view_zakat_status_chart	t	2026-08-08 05:19:44.032399+00	6
171	coordinator	view_house_ownership_chart	t	2026-08-08 05:19:44.033566+00	6
172	coordinator	view_network_performance_chart	t	2026-08-08 05:19:44.034629+00	6
173	coordinator	view_total_students_kpi	t	2026-08-08 05:19:44.035666+00	6
174	coordinator	view_total_teachers_kpi	t	2026-08-08 05:19:44.036707+00	6
175	coordinator	view_teacher_student_ratio_kpi	t	2026-08-08 05:19:44.038086+00	6
176	coordinator	view_avg_attendance_kpi	t	2026-08-08 05:19:44.039422+00	6
177	coordinator	view_coordinator_dashboard	t	2026-08-08 05:19:44.040767+00	6
178	coordinator	manage_permissions	f	2026-08-08 05:19:44.042107+00	6
179	coordinator	manage_forms	f	2026-08-08 05:19:44.043522+00	6
180	teacher	view_dashboard	f	2026-08-08 05:19:44.04481+00	6
181	teacher	view_students	t	2026-08-08 05:19:44.046075+00	6
182	teacher	add_student	f	2026-08-08 05:19:44.047377+00	6
183	teacher	edit_student	f	2026-08-08 05:19:44.048562+00	6
184	teacher	view_teachers	t	2026-08-08 05:19:44.04978+00	6
185	teacher	add_teacher	f	2026-08-08 05:19:44.051075+00	6
186	teacher	view_campus	f	2026-08-08 05:19:44.05226+00	6
187	teacher	add_campus	f	2026-08-08 05:19:44.05328+00	6
188	teacher	view_principals	f	2026-08-08 05:19:44.054274+00	6
189	teacher	add_principal	f	2026-08-08 05:19:44.055258+00	6
190	teacher	view_coordinators	f	2026-08-08 05:19:44.056231+00	6
191	teacher	add_coordinator	f	2026-08-08 05:19:44.057478+00	6
192	teacher	view_attendance	t	2026-08-08 05:19:44.058811+00	6
193	teacher	mark_attendance	t	2026-08-08 05:19:44.060109+00	6
194	teacher	approve_attendance	f	2026-08-08 05:19:44.06138+00	6
195	teacher	view_results	t	2026-08-08 05:19:44.062666+00	6
196	teacher	approve_results	f	2026-08-08 05:19:44.063976+00	6
197	teacher	bulk_import_results	t	2026-08-08 05:19:44.065189+00	6
198	teacher	edit_results	t	2026-08-08 05:19:44.06638+00	6
199	teacher	view_transfers	t	2026-08-08 05:19:44.067516+00	6
200	teacher	view_timetable	t	2026-08-08 05:19:44.068648+00	6
201	teacher	view_requests	t	2026-08-08 05:19:44.069787+00	6
202	teacher	view_promotions	f	2026-08-08 05:19:44.070993+00	6
203	teacher	view_subjects	f	2026-08-08 05:19:44.072246+00	6
204	teacher	view_fees	f	2026-08-08 05:19:44.073454+00	6
205	teacher	manage_fees	f	2026-08-08 05:19:44.074776+00	6
206	teacher	view_grade_distribution_chart	f	2026-08-08 05:19:44.075974+00	6
207	teacher	view_gender_distribution_chart	f	2026-08-08 05:19:44.077159+00	6
208	teacher	view_mother_tongue_chart	f	2026-08-08 05:19:44.078402+00	6
209	teacher	view_religion_chart	f	2026-08-08 05:19:44.079663+00	6
210	teacher	view_enrollment_trend_chart	f	2026-08-08 05:19:44.08097+00	6
211	teacher	view_age_distribution_chart	f	2026-08-08 05:19:44.082259+00	6
212	teacher	view_weekly_attendance_chart	f	2026-08-08 05:19:44.083539+00	6
213	teacher	view_zakat_status_chart	f	2026-08-08 05:19:44.084858+00	6
214	teacher	view_house_ownership_chart	f	2026-08-08 05:19:44.086175+00	6
215	teacher	view_network_performance_chart	t	2026-08-08 05:19:44.087475+00	6
216	teacher	view_total_students_kpi	f	2026-08-08 05:19:44.088808+00	6
217	teacher	view_total_teachers_kpi	f	2026-08-08 05:19:44.090154+00	6
218	teacher	view_teacher_student_ratio_kpi	f	2026-08-08 05:19:44.091592+00	6
219	teacher	view_avg_attendance_kpi	f	2026-08-08 05:19:44.092909+00	6
220	teacher	view_teacher_dashboard	t	2026-08-08 05:19:44.094184+00	6
221	teacher	manage_permissions	f	2026-08-08 05:19:44.095473+00	6
222	teacher	manage_forms	f	2026-08-08 05:19:44.096775+00	6
223	donor	view_dashboard	t	2026-08-08 05:19:44.097995+00	6
224	donor	view_superadmin_dashboard	f	2026-08-08 05:19:44.099205+00	6
225	donor	view_students	t	2026-08-08 05:19:44.100421+00	6
226	donor	add_student	f	2026-08-08 05:19:44.101636+00	6
227	donor	edit_student	f	2026-08-08 05:19:44.102934+00	6
228	donor	view_teachers	t	2026-08-08 05:19:44.104144+00	6
229	donor	add_teacher	f	2026-08-08 05:19:44.105377+00	6
230	donor	view_coordinators	t	2026-08-08 05:19:44.106608+00	6
231	donor	add_coordinator	f	2026-08-08 05:19:44.107831+00	6
232	donor	view_principals	t	2026-08-08 05:19:44.109047+00	6
233	donor	add_principal	f	2026-08-08 05:19:44.110127+00	6
234	donor	view_campus	t	2026-08-08 05:19:44.111266+00	6
235	donor	add_campus	f	2026-08-08 05:19:44.112338+00	6
236	donor	view_attendance	f	2026-08-08 05:19:44.113381+00	6
237	donor	mark_attendance	f	2026-08-08 05:19:44.1144+00	6
238	donor	approve_attendance	f	2026-08-08 05:19:44.115424+00	6
239	donor	view_results	f	2026-08-08 05:19:44.116428+00	6
240	donor	approve_results	f	2026-08-08 05:19:44.117433+00	6
241	donor	bulk_import_results	f	2026-08-08 05:19:44.118489+00	6
242	donor	edit_results	f	2026-08-08 05:19:44.119531+00	6
243	donor	view_transfers	f	2026-08-08 05:19:44.12053+00	6
244	donor	view_timetable	f	2026-08-08 05:19:44.121603+00	6
245	donor	view_requests	f	2026-08-08 05:19:44.122628+00	6
246	donor	view_promotions	f	2026-08-08 05:19:44.123713+00	6
247	donor	view_subjects	f	2026-08-08 05:19:44.12475+00	6
248	donor	view_grade_distribution_chart	t	2026-08-08 05:19:44.125789+00	6
249	donor	view_gender_distribution_chart	t	2026-08-08 05:19:44.126867+00	6
250	donor	view_mother_tongue_chart	t	2026-08-08 05:19:44.127901+00	6
251	donor	view_religion_chart	t	2026-08-08 05:19:44.128961+00	6
252	donor	view_enrollment_trend_chart	t	2026-08-08 05:19:44.130042+00	6
253	donor	view_age_distribution_chart	t	2026-08-08 05:19:44.131045+00	6
254	donor	view_weekly_attendance_chart	t	2026-08-08 05:19:44.132127+00	6
255	donor	view_zakat_status_chart	f	2026-08-08 05:19:44.133188+00	6
256	donor	view_house_ownership_chart	t	2026-08-08 05:19:44.134277+00	6
257	donor	view_network_performance_chart	t	2026-08-08 05:19:44.135344+00	6
258	donor	view_total_students_kpi	t	2026-08-08 05:19:44.136333+00	6
259	donor	view_total_teachers_kpi	t	2026-08-08 05:19:44.137423+00	6
260	donor	view_teacher_student_ratio_kpi	t	2026-08-08 05:19:44.138487+00	6
261	donor	view_avg_attendance_kpi	t	2026-08-08 05:19:44.139493+00	6
262	donor	manage_permissions	f	2026-08-08 05:19:44.140531+00	6
263	donor	manage_forms	f	2026-08-08 05:19:44.141624+00	6
264	accounts_officer	view_dashboard	t	2026-08-08 05:19:44.142694+00	6
265	accounts_officer	view_students	t	2026-08-08 05:19:44.143769+00	6
266	accounts_officer	view_fees	t	2026-08-08 05:19:44.144816+00	6
267	accounts_officer	manage_fees	t	2026-08-08 05:19:44.145979+00	6
268	accounts_officer	view_accounts_dashboard	t	2026-08-08 05:19:44.147186+00	6
269	admissions_counselor	view_dashboard	t	2026-08-08 05:19:44.148291+00	6
270	admissions_counselor	view_students	t	2026-08-08 05:19:44.149463+00	6
271	admissions_counselor	add_student	t	2026-08-08 05:19:44.15063+00	6
272	admissions_counselor	edit_student	t	2026-08-08 05:19:44.151633+00	6
273	admissions_counselor	view_campus	t	2026-08-08 05:19:44.152701+00	6
274	admissions_counselor	view_admissions_dashboard	t	2026-08-08 05:19:44.153868+00	6
275	compliance_officer	view_dashboard	t	2026-08-08 05:19:44.154929+00	6
276	compliance_officer	view_students	t	2026-08-08 05:19:44.155983+00	6
277	compliance_officer	view_attendance	t	2026-08-08 05:19:44.15714+00	6
278	compliance_officer	view_results	t	2026-08-08 05:19:44.158413+00	6
279	compliance_officer	view_campus	t	2026-08-08 05:19:44.159788+00	6
280	compliance_officer	view_compliance_dashboard	t	2026-08-08 05:19:44.16113+00	6
281	student	view_dashboard	t	2026-08-08 05:19:44.162455+00	6
282	student	view_student_dashboard	t	2026-08-08 05:19:44.163803+00	6
\.


--
-- Data for Name: users_subscription_plan; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_subscription_plan (id, name, max_users, max_students, max_campuses, description, base_price, price_per_student, price_per_user, is_enterprise, is_active, created_at, updated_at, created_by_id) FROM stdin;
\.


--
-- Data for Name: users_system_version; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_system_version (id, version, build, release_notes, created_at, released_by_id) FROM stdin;
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_user (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, email, username, is_org_admin, role, phone_number, biometric_id, photo, is_verified, last_login_ip, has_changed_default_password, token_version, created_at, updated_at, campus_id, organization_id, is_deleted) FROM stdin;
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- Name: campus_campus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.campus_campus_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 43, true);


--
-- Name: global_counters_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.global_counters_id_seq', 1, false);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 1, false);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 1, false);


--
-- Name: users_organization_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_organization_id_seq', 1, false);


--
-- Name: users_password_change_otp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_password_change_otp_id_seq', 1, false);


--
-- Name: users_role_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_role_permission_id_seq', 282, true);


--
-- Name: users_subscription_plan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_subscription_plan_id_seq', 1, false);


--
-- Name: users_system_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_system_version_id_seq', 1, false);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_user_id_seq', 1, false);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: campus_campus campus_campus_organization_id_campus_id_6e6a10b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campus_campus
    ADD CONSTRAINT campus_campus_organization_id_campus_id_6e6a10b0_uniq UNIQUE (organization_id, campus_id);


--
-- Name: campus_campus campus_campus_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campus_campus
    ADD CONSTRAINT campus_campus_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: global_counters global_counters_key_organization_id_d5101fd5_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.global_counters
    ADD CONSTRAINT global_counters_key_organization_id_d5101fd5_uniq UNIQUE (key, organization_id);


--
-- Name: global_counters global_counters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.global_counters
    ADD CONSTRAINT global_counters_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: users_organization users_organization_code_prefix_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_organization
    ADD CONSTRAINT users_organization_code_prefix_key UNIQUE (code_prefix);


--
-- Name: users_organization users_organization_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_organization
    ADD CONSTRAINT users_organization_pkey PRIMARY KEY (id);


--
-- Name: users_organization users_organization_subdomain_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_organization
    ADD CONSTRAINT users_organization_subdomain_key UNIQUE (subdomain);


--
-- Name: users_password_change_otp users_password_change_otp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_password_change_otp
    ADD CONSTRAINT users_password_change_otp_pkey PRIMARY KEY (id);


--
-- Name: users_password_change_otp users_password_change_otp_session_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_password_change_otp
    ADD CONSTRAINT users_password_change_otp_session_token_key UNIQUE (session_token);


--
-- Name: users_role_permission users_role_permission_organization_id_role_per_a292c0f9_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_role_permission
    ADD CONSTRAINT users_role_permission_organization_id_role_per_a292c0f9_uniq UNIQUE (organization_id, role, permission_codename);


--
-- Name: users_role_permission users_role_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_role_permission
    ADD CONSTRAINT users_role_permission_pkey PRIMARY KEY (id);


--
-- Name: users_subscription_plan users_subscription_plan_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_subscription_plan
    ADD CONSTRAINT users_subscription_plan_name_key UNIQUE (name);


--
-- Name: users_subscription_plan users_subscription_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_subscription_plan
    ADD CONSTRAINT users_subscription_plan_pkey PRIMARY KEY (id);


--
-- Name: users_system_version users_system_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_system_version
    ADD CONSTRAINT users_system_version_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: campus_campus_organization_id_25fc0bcf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX campus_campus_organization_id_25fc0bcf ON public.campus_campus USING btree (organization_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: global_counters_organization_id_625e0302; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX global_counters_organization_id_625e0302 ON public.global_counters USING btree (organization_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: users_organization_code_prefix_71681ed5_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_organization_code_prefix_71681ed5_like ON public.users_organization USING btree (code_prefix varchar_pattern_ops);


--
-- Name: users_organization_created_by_id_c2e128b3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_organization_created_by_id_c2e128b3 ON public.users_organization USING btree (created_by_id);


--
-- Name: users_organization_plan_id_53df4834; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_organization_plan_id_53df4834 ON public.users_organization USING btree (plan_id);


--
-- Name: users_organization_subdomain_01e18408_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_organization_subdomain_01e18408_like ON public.users_organization USING btree (subdomain varchar_pattern_ops);


--
-- Name: users_password_change_otp_session_token_1df3b106_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_password_change_otp_session_token_1df3b106_like ON public.users_password_change_otp USING btree (session_token varchar_pattern_ops);


--
-- Name: users_password_change_otp_user_id_b291e3c0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_password_change_otp_user_id_b291e3c0 ON public.users_password_change_otp USING btree (user_id);


--
-- Name: users_role_permission_organization_id_f881f577; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_role_permission_organization_id_f881f577 ON public.users_role_permission USING btree (organization_id);


--
-- Name: users_subscription_plan_created_by_id_46fc1f1f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_subscription_plan_created_by_id_46fc1f1f ON public.users_subscription_plan USING btree (created_by_id);


--
-- Name: users_subscription_plan_name_a206d1ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_subscription_plan_name_a206d1ec_like ON public.users_subscription_plan USING btree (name varchar_pattern_ops);


--
-- Name: users_system_version_released_by_id_a884d77d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_system_version_released_by_id_a884d77d ON public.users_system_version USING btree (released_by_id);


--
-- Name: users_user_campus_id_deccb3a1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_campus_id_deccb3a1 ON public.users_user USING btree (campus_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_organization_id_70643736; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_organization_id_70643736 ON public.users_user USING btree (organization_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: campus_campus campus_campus_organization_id_25fc0bcf_fk_users_organization_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campus_campus
    ADD CONSTRAINT campus_campus_organization_id_25fc0bcf_fk_users_organization_id FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: global_counters global_counters_organization_id_625e0302_fk_users_org; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.global_counters
    ADD CONSTRAINT global_counters_organization_id_625e0302_fk_users_org FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_users_use FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_organization users_organization_created_by_id_c2e128b3_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_organization
    ADD CONSTRAINT users_organization_created_by_id_c2e128b3_fk_users_user_id FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_organization users_organization_plan_id_53df4834_fk_users_sub; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_organization
    ADD CONSTRAINT users_organization_plan_id_53df4834_fk_users_sub FOREIGN KEY (plan_id) REFERENCES public.users_subscription_plan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_password_change_otp users_password_change_otp_user_id_b291e3c0_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_password_change_otp
    ADD CONSTRAINT users_password_change_otp_user_id_b291e3c0_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_role_permission users_role_permissio_organization_id_f881f577_fk_users_org; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_role_permission
    ADD CONSTRAINT users_role_permissio_organization_id_f881f577_fk_users_org FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_subscription_plan users_subscription_plan_created_by_id_46fc1f1f_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_subscription_plan
    ADD CONSTRAINT users_subscription_plan_created_by_id_46fc1f1f_fk_users_user_id FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_system_version users_system_version_released_by_id_a884d77d_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_system_version
    ADD CONSTRAINT users_system_version_released_by_id_a884d77d_fk_users_user_id FOREIGN KEY (released_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user users_user_campus_id_deccb3a1_fk_campus_campus_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_campus_id_deccb3a1_fk_campus_campus_id FOREIGN KEY (campus_id) REFERENCES public.campus_campus(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user users_user_organization_id_70643736_fk_users_organization_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_organization_id_70643736_fk_users_organization_id FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 2VXy61MFKZER1RbLlsdzHhsrEqFCwiJMe3pccgNqj3FbLgFYS5hLbOCIhmcgd52

