# Generated by Django 5.2.16 on 2026-08-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentitem_central_org_id_contentitem_tenant_id_and_more'),
        ('users', '0010_alter_rolepermission_permission_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcontentprogress',
            name='central_user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentcontentprogress',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='studentcontentprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('central_user_id__isnull', False)), fields=('central_user_id', 'lesson'), name='uniq_central_user_lesson_progress'),
        ),
    ]
