# Generated by Django 5.2.17 on 2026-08-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='central_org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
