# Generated by Django 5.0.1 on 2025-11-24 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.UUIDField(db_index=True)),
                ('sender_id', models.UUIDField(db_index=True)),
                ('message', models.TextField()),
                ('mentions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket_id'], name='chat_messag_ticket__d35b54_idx'), models.Index(fields=['sender_id'], name='chat_messag_sender__e8b05b_idx'), models.Index(fields=['ticket_id', 'created_at'], name='chat_messag_ticket__d5a71c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ticket Participant',
                'verbose_name_plural': 'Ticket Participants',
                'db_table': 'ticket_participants',
                'indexes': [models.Index(fields=['ticket_id'], name='ticket_part_ticket__f29070_idx'), models.Index(fields=['user_id'], name='ticket_part_user_id_c38cad_idx')],
                'unique_together': {('ticket_id', 'user_id')},
            },
        ),
    ]
