# Generated by Django 5.2.14 on 2026-05-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_grade_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='assigned_coordinator_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='assigned_coordinator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
