# Generated by Django 5.2.14 on 2026-05-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_level_add_coordinator_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='assigned_coordinator_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
