# Generated by Django 5.2.17 on 2026-08-07 04:55
#
# Phase D-R1: copied from staff-service's teachers_staff_migrations/0008
# (identical Teacher model fields, identical migration chain up to 0007 in
# both services' independent per-service migration histories for the
# vendored teachers/ app — see MIGRATION_MODULES in each settings.py).
# attendance-service's own copy of this migration was missing entirely
# (stuck at 0007), which meant its local teachers_teacher table never got
# these 3 columns — found live via a 500 while proving central-auth tokens
# work across services (HasAttendanceViewPermission's central branch,
# via DualHasAttendanceViewPermission's find_teacher(), queries
# central_user_id). See docs/PHASE_D_R1R2R3_CUTOVER_RESULT.md.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacher_role_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='central_classroom_assigned_by_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='central_user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
