# Generated by Django 5.0.1 on 2026-07-29 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_remove_employeeassignment_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tenant / customer name', max_length=255)),
                ('tenant_code', models.CharField(help_text='Short code for the tenant (e.g. VMST)', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalized from organization.tenant — set automatically on save. One employee = one tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.tenant'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Paying customer this organization belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='employees.tenant'),
        ),
    ]
