# Generated by Django 5.0.1 on 2026-08-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_tenant_employee_tenant_organization_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='legacy_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Original SMS users_user.id (Phase B import key), null if not imported from SMS', null=True, unique=True),
        ),
    ]
