# Generated by Django 5.0.1 on 2026-08-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_employee_legacy_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='legacy_org_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Original org-service Organization.id (Phase D-b5 sync key), null if not synced from SMS', null=True, unique=True),
        ),
    ]
