# Generated by Django 5.0.1 on 2025-11-24 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('ticket_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_status_changed', 'Ticket Status Changed'), ('ticket_mentioned', 'Ticket Mentioned'), ('approval_requested', 'Approval Requested'), ('approval_decision', 'Approval Decision'), ('ticket_postponed', 'Ticket Postponed'), ('ticket_reminder', 'Ticket Reminder'), ('auto_close_reminder', 'Auto Close Reminder'), ('ticket_reopened', 'Ticket Reopened'), ('subticket_created', 'SubTicket Created'), ('subticket_status_changed', 'SubTicket Status Changed'), ('message_received', 'Message Received')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='notificatio_user_id_e78525_idx'), models.Index(fields=['ticket_id'], name='notificatio_ticket__df5b99_idx'), models.Index(fields=['type'], name='notificatio_type_8a8a78_idx'), models.Index(fields=['user_id', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
