# Generated by Django 5.2.15 on 2026-07-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_classtimetable_nullable_subject_teacher'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shifttiming',
            name='unique_shift_period_name',
        ),
    ]
