# Generated by Django 5.2.17 on 2026-08-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_remove_shifttiming_unique_shift_period_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='central_created_by_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='central_org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='central_teacher_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='central_org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='central_org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='central_created_by_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='central_org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='central_teacher_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
