# Generated by Django 5.2.17 on 2026-08-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacher_role_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='central_classroom_assigned_by_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='central_user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        # Phase C12: makemigrations also proposed `CreateModel` for
        # TeacherSubjectAssignment — a PRE-EXISTING gap, unrelated to
        # central-auth. That model (teachers/models.py) has apparently
        # never had a migration (migration numbering jumps 0004 -> 0006,
        # skipping 0005 entirely) and its own FK to `timetable.subject`
        # can't even be satisfied — `timetable` is not an installed app in
        # staff-service, nor is it vendored (confirmed: no timetable/
        # directory, no Dockerfile COPY step, no INSTALLED_APPS entry).
        # TeacherSubjectAssignmentViewSet (teachers/views.py) has
        # therefore never worked in this environment. Deliberately
        # excluded from this migration — flagged in
        # docs/PHASE_C12_STAFF_SERVICE_RESULT.md as a pre-existing,
        # out-of-scope gap, not fixed here.
    ]
