from django.core.management.base import BaseCommand
from users.models import RolePermission

class Command(BaseCommand):
    help = 'Seed default role permissions for all system roles'

    def handle(self, *args, **kwargs):
        roles = {
            'ADMIN': {
                'view_admin_dashboard': True,
                'view_coordinator_dashboard': True,
                'view_teacher_dashboard': True,
                'view_student_dashboard': True,
                'view_analytics': True,
                'manage_courses': True,
                'manage_classes': True,
                'manage_enrollments': True,
                'manage_assignments': True,
                'manage_certifications': True,
                'id_generator': True,
                'view_deposits': True,
                'view_entrance_leads': True,
                'manage_refunds': True,
                'manage_transfers': True,
                'manage_receipts': True,
                'manage_users': True,
                'manage_teachers': True,
                'view_students': True,
                'view_fees': True,
                'view_attendance': True,
                'manage_notifications': True,
            },
            'COORDINATOR': {
                'view_admin_dashboard': True,
                'view_coordinator_dashboard': True,
                'view_teacher_dashboard': True,
                'view_student_dashboard': False,
                'view_analytics': True,
                'manage_courses': False,
                'manage_classes': True,
                'manage_enrollments': True,
                'manage_assignments': True,
                'manage_certifications': True,
                'id_generator': True,
                'view_deposits': False,
                'view_entrance_leads': False,
                'manage_refunds': False,
                'manage_transfers': True,
                'manage_receipts': False,
                'manage_users': True,
                'manage_teachers': True,
                'view_students': True,
                'view_fees': True,
                'view_attendance': True,
                'manage_notifications': True,
            },
            'ACCOUNT_OFFICER': {
                'view_admin_dashboard': True,
                'view_coordinator_dashboard': False,
                'view_teacher_dashboard': False,
                'view_student_dashboard': False,
                'view_analytics': False,
                'manage_courses': False,
                'manage_classes': False,
                'manage_enrollments': False,
                'manage_assignments': False,
                'manage_certifications': False,
                'id_generator': False,
                'view_deposits': True,
                'view_entrance_leads': True,
                'manage_refunds': False,
                'manage_transfers': False,
                'manage_receipts': True,
                'manage_users': False,
                'manage_teachers': False,
                'view_students': False,
                'view_fees': True,
                'view_attendance': False,
                'manage_notifications': False,
            },
            'TEACHER': {
                'view_admin_dashboard': False,
                'view_coordinator_dashboard': False,
                'view_teacher_dashboard': True,
                'view_student_dashboard': False,
                'view_analytics': False,
                'manage_courses': False,
                'manage_classes': False,
                'manage_enrollments': False,
                'manage_assignments': True,
                'manage_certifications': False,
                'id_generator': False,
                'view_deposits': False,
                'view_entrance_leads': False,
                'manage_refunds': False,
                'manage_transfers': False,
                'manage_receipts': False,
                'manage_users': False,
                'manage_teachers': False,
                'view_students': True,
                'view_attendance': True,
                'manage_notifications': False,
            },
            'STUDENT': {
                'view_admin_dashboard': False,
                'view_coordinator_dashboard': False,
                'view_teacher_dashboard': False,
                'view_student_dashboard': True,
                'view_analytics': False,
                'manage_courses': False,
                'manage_classes': False,
                'manage_enrollments': False,
                'manage_assignments': False,
                'manage_certifications': False,
                'id_generator': False,
                'view_deposits': False,
                'view_entrance_leads': False,
                'manage_refunds': False,
                'manage_transfers': False,
                'manage_receipts': False,
                'manage_users': False,
                'manage_teachers': False,
                'view_students': False,
                'view_fees': True,
                'view_attendance': False,
                'manage_notifications': False,
            },
            'TA': {
                'view_admin_dashboard': False,
                'view_coordinator_dashboard': False,
                'view_teacher_dashboard': True,
                'view_student_dashboard': False,
                'view_analytics': False,
                'manage_courses': False,
                'manage_classes': False,
                'manage_enrollments': False,
                'manage_assignments': True,
                'manage_certifications': False,
                'id_generator': False,
                'view_deposits': False,
                'view_entrance_leads': False,
                'manage_refunds': False,
                'manage_transfers': False,
                'manage_receipts': False,
                'manage_users': False,
                'manage_teachers': False,
                'view_students': True,
                'view_attendance': True,
                'manage_notifications': False,
            },
        }

        for role, permissions in roles.items():
            perm, created = RolePermission.objects.update_or_create(
                role=role,
                defaults={'permissions': permissions}
            )
            status = 'Created' if created else 'Updated'
            self.stdout.write(self.style.SUCCESS(f'{status} permissions for {role}'))

        self.stdout.write(self.style.SUCCESS('All role permissions seeded successfully'))
