# Generated by Django 5.2.17 on 2026-08-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_grades_data_evening_to_afternoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='central_org_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
