# Generated by Django 5.2.16 on 2026-07-14 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus_id', models.CharField(max_length=50, unique=True)),
                ('campus_code', models.CharField(max_length=20)),
                ('campus_name', models.CharField(max_length=255)),
                ('campus_type', models.CharField(choices=[('main', 'Main'), ('branch', 'Branch')], default='branch', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('shift_available', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('both', 'Both')], default='morning', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('campus_head_name', models.CharField(blank=True, max_length=255, null=True)),
                ('campus_head_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_capacity', models.IntegerField(default=200)),
                ('total_classrooms', models.IntegerField(default=0)),
                ('total_staff_rooms', models.IntegerField(default=0)),
                ('labs', models.BooleanField(default=False)),
                ('library', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
                ('internet_available', models.BooleanField(default=False)),
                ('power_backup', models.BooleanField(default=False)),
                ('canteen_facility', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
                'ordering': ['campus_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('max_users', models.IntegerField(default=100)),
                ('max_students', models.IntegerField(default=500)),
                ('max_campuses', models.IntegerField(default=5)),
                ('enabled_features', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shift', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='orgs.campus')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='orgs.organization')),
            ],
            options={
                'verbose_name_plural': 'Levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='orgs.campus')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='orgs.level')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='orgs.organization')),
            ],
            options={
                'verbose_name_plural': 'Grades',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='orgs.organization'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=10)),
                ('shift', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.IntegerField(default=40)),
                ('class_teacher_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='orgs.campus')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='orgs.grade')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='orgs.organization')),
            ],
            options={
                'verbose_name_plural': 'Classrooms',
                'ordering': ['grade__name', 'section'],
                'unique_together': {('grade', 'section')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together={('organization', 'campus_code')},
        ),
    ]
