# Generated by Django 5.0.1 on 2025-11-24 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.UUIDField(db_index=True)),
                ('approver_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('documents', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
                'db_table': 'approvals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket_id'], name='approvals_ticket__e4fdc5_idx'), models.Index(fields=['approver_id'], name='approvals_approve_41f915_idx'), models.Index(fields=['status'], name='approvals_status_658918_idx')],
            },
        ),
    ]
