# Generated by Django 5.0.6 on 2026-01-21 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=100)),
                ('course_id', models.UUIDField()),
                ('enrollment_id', models.UUIDField(blank=True, null=True)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('verification_code', models.CharField(max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('course_title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('percentile', models.IntegerField(blank=True, null=True)),
                ('institution_name', models.CharField(default='AIT Institute', max_length=255)),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'certifications_certification',
                'ordering': ['-issued_date'],
            },
        ),
    ]
