# Generated by Django 5.0.6 on 2025-12-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_studentprofile_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coordinatorprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
