# Generated by Django 5.0.6 on 2025-12-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_adminprofile_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coordinatorprofile',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
