# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('course_id', models.UUIDField(help_text='Reference to Course in Course Service')),
                ('specialization_id', models.UUIDField(blank=True, help_text='Reference to Specialization in Course Service', null=True)),
                ('passing_marks', models.IntegerField(default=70)),
                ('total_marks', models.IntegerField(default=100)),
                ('duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('is_required', models.BooleanField(default=True, help_text='Is test required for enrollment?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('user_email', models.EmailField(max_length=254)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('expired', 'Expired')], default='ongoing', max_length=20)),
                ('is_passed', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('lms_enrollment_id', models.UUIDField(blank=True, help_text='Stored after successful call to Course Service', null=True)),
                ('enrollment_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='none', max_length=20)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'verbose_name_plural': 'TestAttempts',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('marks', models.IntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['course_id', 'specialization_id'], name='tests_test_course__e3205a_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user_id', 'test'], name='tests_testa_user_id_47190b_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['status'], name='tests_testa_status_f39dfa_idx'),
        ),
    ]
