# Generated by Django 5.0.6 on 2026-01-05 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_entrancelead'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('course_id', models.UUIDField()),
                ('test_attempt_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Entrance Leads',
            },
        ),
        migrations.RenameIndex(
            model_name='test',
            new_name='tests_test_course__e05404_idx',
            old_name='tests_test_course__e3205a_idx',
        ),
        migrations.RenameIndex(
            model_name='testattempt',
            new_name='tests_testa_user_id_a9b45d_idx',
            old_name='tests_testa_user_id_47190b_idx',
        ),
        migrations.RenameIndex(
            model_name='testattempt',
            new_name='tests_testa_status_ebfe54_idx',
            old_name='tests_testa_status_f39dfa_idx',
        ),
    ]
