# Generated by Django 5.0.6 on 2026-01-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_entrancelead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancelead',
            name='test_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
