# Generated by Django 5.0.6 on 2026-01-20 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_entrancelead_test_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interviewer_id', models.UUIDField(blank=True, null=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='tests.entrancelead')),
            ],
            options={
                'verbose_name_plural': 'Interviews',
            },
        ),
    ]
