# Generated by Django 5.0.6 on 2026-03-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancelead',
            name='course_name_requested',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='has_paid_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='lead_auto_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entrancelead',
            name='course_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
