# Generated by Django 5.0.6 on 2026-03-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_entrancelead_course_name_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancelead',
            name='course_code_requested',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
