# Generated by Django 5.0.6 on 2026-04-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_entrancelead_course_code_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancelead',
            name='scheduled_class_id',
            field=models.UUIDField(blank=True, help_text='Session/ScheduledClass selected during registration', null=True),
        ),
    ]
