# Generated by Django 5.0.6 on 2026-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_entrancelead_scheduled_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancelead',
            name='father_guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='is_terms_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='language_course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='last_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='relationship_to_student',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='studied_at_idara',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='study_work_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='study_work_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='studying_at_idara',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
