# Generated by Django 5.0.6 on 2026-04-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_entrancelead_father_guardian_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancelead',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='cnic_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
