# Generated by Django 5.0.6 on 2026-04-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_entrancelead_age_entrancelead_cnic_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancelead',
            name='course_name_requested',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrancelead',
            name='last_qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrancelead',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
