# Generated by Django 5.0.6 on 2026-04-29 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_adminactionlog_entrancelead_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancelead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='converted_to_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrancelead',
            name='lms_user_id',
            field=models.UUIDField(blank=True, help_text='UUID of the User record in auth-service after account creation', null=True),
        ),
        migrations.CreateModel(
            name='ReceiptCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_name', models.CharField(max_length=255)),
                ('cnic_number', models.CharField(blank=True, help_text='Copied from EntranceLead at creation', max_length=20, null=True)),
                ('course_id', models.UUIDField(blank=True, null=True)),
                ('scheduled_class_id', models.UUIDField(blank=True, help_text='Session selected by student at registration', null=True)),
                ('test_score', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('added_by_admin', models.UUIDField(blank=True, null=True)),
                ('added_to_system_at', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('lms_account_created', models.BooleanField(default=False)),
                ('lms_user_id', models.UUIDField(blank=True, null=True)),
                ('deposit_amount', models.IntegerField(default=5000)),
                ('bag_taken', models.BooleanField(default=True)),
                ('bag_fee', models.IntegerField(default=1000)),
                ('bag_paid', models.BooleanField(default=False)),
                ('bag_waived', models.BooleanField(default=False)),
                ('id_card_taken', models.BooleanField(default=True)),
                ('id_card_fee', models.IntegerField(default=500)),
                ('id_card_paid', models.BooleanField(default=False)),
                ('id_card_waived', models.BooleanField(default=False)),
                ('is_waived', models.BooleanField(default=False)),
                ('is_returned', models.BooleanField(default=False)),
                ('amount_returned', models.IntegerField(default=0)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, help_text='The EntranceLead that triggered this receipt code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_codes', to='tests.entrancelead')),
            ],
            options={
                'verbose_name_plural': 'Receipt Codes',
            },
        ),
    ]
