# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_branch_entrancelead_branch_receiptcode_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcode',
            name='certificate_taken',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='certificate_fee',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='certificate_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='certificate_waived',
            field=models.BooleanField(default=False),
        ),
    ]
