# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_receiptcode_certificate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('true_false', 'True/False'), ('multiple_choice', 'Multiple Choice')], default='single_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_option_images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
