# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_question_type_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order of questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.CharField(blank=True, default='', help_text='Comma-separated correct answers for multiple_choice questions', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Questions'},
        ),
    ]
