# Generated by Django 5.0.6 on 2026-06-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_question_order_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptcode',
            name='bag_fee',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='receiptcode',
            name='deposit_amount',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='receiptcode',
            name='id_card_fee',
            field=models.IntegerField(default=200),
        ),
        migrations.AddIndex(
            model_name='entrancelead',
            index=models.Index(fields=['email'], name='tests_entra_email_57c818_idx'),
        ),
        migrations.AddIndex(
            model_name='entrancelead',
            index=models.Index(fields=['status'], name='tests_entra_status_80771d_idx'),
        ),
        migrations.AddIndex(
            model_name='entrancelead',
            index=models.Index(fields=['course_id'], name='tests_entra_course__6a1576_idx'),
        ),
        migrations.AddIndex(
            model_name='entrancelead',
            index=models.Index(fields=['is_deleted'], name='tests_entra_is_dele_b49923_idx'),
        ),
        migrations.AddIndex(
            model_name='entrancelead',
            index=models.Index(fields=['-created_at'], name='tests_entra_created_4098aa_idx'),
        ),
        migrations.AddIndex(
            model_name='entrancelead',
            index=models.Index(fields=['lead_auto_id'], name='tests_entra_lead_au_e43b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptcode',
            index=models.Index(fields=['student_email'], name='tests_recei_student_3b6353_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptcode',
            index=models.Index(fields=['verified'], name='tests_recei_verifie_7080d2_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptcode',
            index=models.Index(fields=['is_deleted'], name='tests_recei_is_dele_cb38ba_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptcode',
            index=models.Index(fields=['code'], name='tests_recei_code_068d12_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user_email'], name='tests_testa_user_em_302b15_idx'),
        ),
    ]
