# Generated by Django 5.0.6 on 2026-07-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_alter_receiptcode_bag_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancelead',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='receiptcode',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='FK to org-service Organization', null=True),
        ),
    ]
